
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    production: false,
    SMARTY_AUTH_ID: 'undefined'
    SMARTY_TOKEN: 'undefined'
  };
