
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    production: false,
    SMARTY_AUTH_ID: '6b6533ca-6c82-4050-7351-a8c9608d42e7'
    SMARTY_TOKEN: 'WHaV2mmPXCxtYedAtRr7'
  };
