export const APL_ARR_COMMON = [
    {
    id: '1',
    aplId: 'APL_51',
    aplType: 'Large Employer',
    aplSubType: 'CHIP',
    aplIssue: 'Individual Exemption',
    aplStage: 'Intake',
    aplLink: 'intake',
    aplStatus: 'new',
    aplSubmittedBy: "Appellant",
    adjudDeadline: '',
    createdOn: '2022-02-30T12:49:11.33',
    createdBy: 'User Name',
    expedited: true,
    highProfile: 'Boolean or String?',
    hearingDate: "2024-01-30T12:59:11.33",
    hearingId: "HEARING_ID_01",
    location: 'Appeal Intake WB',
    nextActionDate: '2023-12-30T12:50:11.33',
    mdcd: 'true',
    notes: 'notes for APL_51',
    phase: 'phase should be here',
    phaseChangedDate: "",
    planYear: "2024",
    reopenPhase: "",
    receiptType: "On-line",
    recieptDate: "2022-05-30T12:59:11.33",
    rfiDate: '2024-04-30T12:59:11.33',
    status: 'New',
    updatedOn: '',
    updatedBy: '',
    contacts: [
        {
            contactId: "934343e2-c2ab-41ff-a04a-ef8a511807d9",
            appealId: "APL-51",
            createDateTime: "2022-05-11T11:36:26",
            createOprtr: null,
            creaeOptrName: null,
            updateDateTime: "2022-08-02T15:29:38",
            updateOptr: null,
            updateOprtName: null,
            type: "",
            prsnType: "",
            primaryContact: false,
            sfx: "",
            firstName: "TestF",
            middleName: "TestM",
            lastName: "TestL",
            Dob: "1986-04-12",
            emplrName: "",
            dtSgnd: null,
            sgntrInd: false,
            adrSameAsApllant: false,
            authrztn: "",
            ubleToContact: false,
            langAstnc: false,
            spkLang: "",
            wrtnLang: "",
            vrfctnType: "",
            ackAdr: false,
            efctvStrtDt: null,
            efctvEndDt: null,
            authrzgAplntSgtr: false,
            aplntSgndDt: null,
            authrzdRprsntvSgntr: false,
            raprsntvSgndDt: null,
            acAptc: true,
            acMonthlyAmt: 2000,
            acAnnualAmt: 3500,
            acCsr: true,
            acCsrLevel: "true",
            acQhp: false,
            acMdcd: true,
            acChip: true,
            acSep: true,
            acCtstrphc: true,
            acExemption: true,
            acNoAward: true,
            acDisp: "test",
            adacAptc: true,
            adacMonthlyAmt: 123445,
            adacAnnAmount: 1234567,
            adacCsr: true,
            adacCsrLevel: "test1",
            adacQhp: true,
            adacMdcd: true,
            adacChip: true,
            adacSep: true,
            adacCtstrphc: true,
            adacExemp: true,
            adacNoAward: true,
            adacDisp: "djtest1",
            exempEcn: "djtest1",
            exempIndvdlExemp: "test",
            exempBgnDt: "2022-04-13",
            exempEndDt: "2022-04-13",
            exempOutcm: "test",
            exempCmmts: "test",
            pbacAptc: true,
            pbacMonthlyAmt: 123,
            pbacAnnaulAmt: 7456,
            pbacCsr: true,
            pbacCsrLevel: "test",
            pbacPhp: true,
            pbacMdcd: true,
            pbacChip: true,
            pbacSep: true,
            pbacCtstrphc: true,
            pbacExemp: true,
            pbacNoAwd: true,
            pbacDisp: "test",
            ritAnnualIncome: true,
            ritCitizenship: true,
            ritImgrtn: true,
            ritEscMec: true,
            ritNonEscMec: true,
            ritTrbl: true,
            ritMdcd: true,
            sepType: "test",
            sepDnlCrtr: "test",
            sepOutcm: "test",
            sepEfctvDt: "2022-04-12",
            sep: true,
            sepCmmts: "test",
            sepacAptc: true,
            sepacMnthlyAmt: 45634535,
            sepacAnnAmt: 3453678,
            sepacCsr: true,
            sepacCsrLvl: "test",
            sepacQhp: true,
            sepacMdcd: true,
            sepacChip: true,
            sepacSep: true,
            sepacCtstrphc: true,
            sepacExemp: true,
            sepacNoAwd: true,
            sepacDisp: "test",
            ednAptc: true,
            aptcMonthlyAmt: 76684234,
            aptcAnnualAmt: 423245576,
            ednCsr: true,
            ednCsrLevel: "true",
            ednQhp: true,
            ednMedicAid: true,
            ednSep: true,
            ednChip: true,
            ednCstrphc: true,
            ednExempetion: true,
            hicsacAptc: true,
            hicsacMnthlyAmt: 546456,
            hicsacAnnAmt: 55546645646,
            hicsacCsr: true,
            hicsacCsrLvl: "true",
            hicsacQhp: true,
            hicsacMdcd: true,
            hicsacChip: true,
            hicsacSep: true,
            hicsacCtstrphc: true,
            hicsacExemp: true,
            hicsacNoAwd: true,
            hicsacDisp: "test",
            cnstdEdnAptc: true,
            cnstdMonthlyAmt: 45453446,
            cnstdAnnualAmt: 3665643543,
            cnstdEdnCsr: true,
            cnstdEdnCsrLvl: "test",
            cnstdEdnQhp: true,
            cnstdEdnMdcd: true,
            cnstdEdnChip: true,
            cnstdEdnSep: true,
            cnsdtdEdnCtstrphc: true,
            cnstdEdnExemp: true,
            cnstdEdnEcn: "test",
            cnstdEdnDisp: "test",
            cnstdEdnDispDate: "2022-04-12",
            dob: "1986-04-12"
        },
        {
            contactId: "9e7ef627-e09a-4274-906e-8652d0787d85",
            appealId: "APL-51",
            createDateTime: "2022-05-11T11:28:56",
            createOprtr: null,
            creaeOptrName: null,
            updateDateTime: "2022-08-02T15:29:38",
            updateOptr: null,
            updateOprtName: null,
            type: null,
            prsnType: null,
            primaryContact: false,
            sfx: null,
            firstName: "TestF",
            middleName: "TestM",
            lastName: "TestL",
            Dob: null,
            emplrName: null,
            dtSgnd: null,
            sgntrInd: false,
            adrSameAsApllant: false,
            authrztn: null,
            ubleToContact: false,
            langAstnc: false,
            spkLang: null,
            wrtnLang: null,
            vrfctnType: null,
            ackAdr: false,
            efctvStrtDt: null,
            efctvEndDt: null,
            authrzgAplntSgtr: false,
            aplntSgndDt: null,
            authrzdRprsntvSgntr: false,
            raprsntvSgndDt: null,
            acAptc: true,
            acMonthlyAmt: 2000,
            acAnnualAmt: 3500,
            acCsr: true,
            acCsrLevel: "true",
            acQhp: false,
            acMdcd: true,
            acChip: true,
            acSep: true,
            acCtstrphc: true,
            acExemption: true,
            acNoAward: true,
            acDisp: "test",
            adacAptc: true,
            adacMonthlyAmt: 123445,
            adacAnnAmount: 1234567,
            adacCsr: true,
            adacCsrLevel: "test1",
            adacQhp: true,
            adacMdcd: true,
            adacChip: true,
            adacSep: true,
            adacCtstrphc: true,
            adacExemp: true,
            adacNoAward: true,
            adacDisp: "djtest1",
            exempEcn: "djtest1",
            exempIndvdlExemp: "test",
            exempBgnDt: "2022-04-13",
            exempEndDt: "2022-04-13",
            exempOutcm: "test",
            exempCmmts: "test",
            pbacAptc: true,
            pbacMonthlyAmt: 123,
            pbacAnnaulAmt: 7456,
            pbacCsr: true,
            pbacCsrLevel: "test",
            pbacPhp: true,
            pbacMdcd: true,
            pbacChip: true,
            pbacSep: true,
            pbacCtstrphc: true,
            pbacExemp: true,
            pbacNoAwd: true,
            pbacDisp: "test",
            ritAnnualIncome: true,
            ritCitizenship: true,
            ritImgrtn: true,
            ritEscMec: true,
            ritNonEscMec: true,
            ritTrbl: true,
            ritMdcd: true,
            sepType: "test",
            sepDnlCrtr: "test",
            sepOutcm: "test",
            sepEfctvDt: "2022-04-12",
            sep: true,
            sepCmmts: "test",
            sepacAptc: true,
            sepacMnthlyAmt: 45634535,
            sepacAnnAmt: 3453678,
            sepacCsr: true,
            sepacCsrLvl: "test",
            sepacQhp: true,
            sepacMdcd: true,
            sepacChip: true,
            sepacSep: true,
            sepacCtstrphc: true,
            sepacExemp: true,
            sepacNoAwd: true,
            sepacDisp: "test",
            ednAptc: true,
            aptcMonthlyAmt: 76684234,
            aptcAnnualAmt: 423245576,
            ednCsr: true,
            ednCsrLevel: "true",
            ednQhp: true,
            ednMedicAid: true,
            ednSep: true,
            ednChip: true,
            ednCstrphc: true,
            ednExempetion: true,
            hicsacAptc: true,
            hicsacMnthlyAmt: 546456,
            hicsacAnnAmt: 55546645646,
            hicsacCsr: true,
            hicsacCsrLvl: "true",
            hicsacQhp: true,
            hicsacMdcd: true,
            hicsacChip: true,
            hicsacSep: true,
            hicsacCtstrphc: true,
            hicsacExemp: true,
            hicsacNoAwd: true,
            hicsacDisp: "test",
            cnstdEdnAptc: true,
            cnstdMonthlyAmt: 45453446,
            cnstdAnnualAmt: 3665643543,
            cnstdEdnCsr: true,
            cnstdEdnCsrLvl: "test",
            cnstdEdnQhp: true,
            cnstdEdnMdcd: true,
            cnstdEdnChip: true,
            cnstdEdnSep: true,
            cnsdtdEdnCtstrphc: true,
            cnstdEdnExemp: true,
            cnstdEdnEcn: "test",
            cnstdEdnDisp: "test",
            cnstdEdnDispDate: "2022-04-12",
            dob: null
        }
    ],
    intakeObject: {
        accommFlag: false,
        accommReq: [],
        ackNotice: "",
        ackNoticeDate: "",
        ackNoticeGranted: "",
        appCallReleaseHold: false,
        appReasonForAppeal: "",
        decisionDate: "",
        eacmsRecievedDate: "2022-04-30T12:59:11.33",
        eligDecision: "",
        expComments: "My TestingComments",
        expFlag: true,
        expFor: "Expidite",
        expReqGranted: true,
        formType: "Assessment State",
        intakeType: "Return Mail",
        langAssitComments: "",
        langAssitFlag: false,
        languageAssistReq: [{}],
        mktplcDecision: "",
        ndEndDate: "2022-04-30T12:59:11.33",
        ndFlag: true,
        ndName: "My Testing",
        ndStartDate: "2022-04-30T12:59:11.33",
        openStatusDate: "2022-04-30T12:59:11.33",
        pendedReason: "Disaster Extension ",
        pendedReqEndDate: "2022-04-30T12:59:11.332",
        pendedReqStartDate: "2022-04-12T12:59:11.332",
        smah: false,
        state: "",
        stateModel: "SBM",
        xReference: "Some Value",
        xReferenceType: "Appellant on another appeal"
    },
    adjudicationObject: {
        ackmtNtcMailedDate: "2022-04-12",
        acsTaxData: true,
        actnNtcSentDt: null,
        actnneedatcall: "test",
        actnneedbyeaos: "test",
        actntakendt: "2022-04-12",
        adjEffId: "e2fccd15-3e39-4a88-b1d1-96cd50f368cf",
        adjEffInfo: [],
        adjKpiAfourPbDate: "2022-04-12",
        adjKpiAoneDate: "2022-04-12",
        adjKpiAtwoDate: "2022-04-12",
        adjPhase: "test1",
        adjRFIResDates: [],
        afrdbltyPctg: 789,
        aplDcsnDate: "2022-04-12",
        aplInprogNtcSentDt: null,
        aplclsfctndt: null,
        aplfileddt: "2022-04-12",
        aplrcvdmmsdt: "2022-04-12",
        benchMark: true,
        busnsName: "test",
        clsrdt: "2022-04-12",
        cnstdEDNDate: "2022-04-12",
        cnstdEdnApplcnDate: "2022-04-12",
        cnstdEdnAtstdIncome: 535345345345,
        cnstdEdnComments: "test",
        cnstdEdnFplPctg: 345345345345,
        cntstdEdnOutcome: "test",
        createOperator: "DJtest",
        eactCompletedBy: "DJ1",
        eactCompletedDate: "2022-07-14",
        ednAplcnDate: "2022-04-12",
        ednAtstdIncome: 5433453,
        ednComments: "test",
        ednDate: "2022-04-22",
        ednFplPctg: 45654757,
        efctvRqstdDate: "2022-04-12",
        effPhase: "test1",
        escMec: true,
        escMecAfrdblty: "test",
        escMecType: "test",
        evaltnGrntdDate: null,
        evaltnOutcome: null,
        exempComments: "test1",
        exempDocsRequested: "test1",
        exempRequestNumber: 12345,
        exmpPhase: "test1",
        extensionDate: "2022-04-12",
        fairlRcncl: true,
        ftrToolDueDate: "2022-04-12",
        heargdcsndt: "2022-04-12",
        hicsInfo: [],
        hicsMatchAd: true,
        houseHoldIncome: 456,
        icoAtstdIncome: 97793247923,
        id: "02",
        inconsDocuments: [],
        inconsDtls: [],
        inconsResolvedFfm: "test",
        irCicDate: "2022-04-12",
        irCicPerformed: "test",
        irNtcRespDueDt: null,
        irNtcSent: null,
        irNtcStsf: null,
        irNtcStsfDt: null,
        irntcexprtndt: "2022-04-12",
        irntcsentdt: "2022-04-12",
        iroAdrdbltyPctg: "test",
        iroFplPctg: 42424242342342,
        irresprcvddt: "2022-04-12",
        lowstSlfPlanCost: 56565656,
        marFilingSeparately: true,
        marketPlaceAplcnId: null,
        mdcdorchipdnl: null,
        mdcdorchiptrmntn: null,
        mdcdorchipunwinding: null,
        moenDate: "2022-04-12",
        noFinclAstnc: true,
        noRetroactGrntd: false,
        nonEscMec: true,
        nonEscMecType: "test",
        nonTaxFiler: true,
        outcomeWithThreshhold: "test",
        outstandingDocuments: [],
        overFourHundred: true,
        particagree: "test",
        pbEvaluation: [],
        pendBnftComments: "test",
        pendBnftEfctvDate: "2022-04-12",
        pendBnftElgbl: true,
        pendBnftRqstDate: "2022-04-12",
        pendBnftTrmntnDate: "2022-04-12",
        postIRMatchIR: true,
        postIrNtcSent: null,
        postIrNtcSentDt: null,
        postirdt: "2022-04-12",
        premiumAmount: 123,
        priorEnrlmntHstry: null,
        priorIncons: null,
        rdtrmntn: null,
        retroActGrntd: "test1",
        retroActGrntdDate: "2022-04-12",
        retroActRqstdDate: "2022-04-12",
        retroactElgblDt: null,
        retroactRqstd: "test1",
        rfiRespRecvdDt: null,
        rfiResponseDueDt: null,
        rfiSentDate: null,
        rspnsKpiAtwoDate: "2022-04-12",
        rvsdIrDt: null,
        rvsdirelgbl: "test",
        rvsdirenddt: "2022-04-12",
        rvsdiroutcm: "test",
        rvsdirrsn: "test",
        rvsdirrspns: "test",
        rvsdirstartdt: "2022-04-12",
        schdlheargdt: "2022-04-12",
        schdlheargsentdt: "2022-04-12",
        secondIrElgbl: null,
        sepEndDt: null,
        sepExprtnDate: "2022-04-12",
        sepGrntd: null,
        sepMatchAd: true,
        sepOpenDt: null,
        sercoEfctatnDt: null,
        spclNtcGrp: true,
        timely: null,
        tolrsn: "test",
        tolstartdt: "2022-04-12",
        tolstopdt: "2022-04-12",
        underOneHundFpl: true,
        updateOperator: "test1",
        verificationTools: [],
    },
    hearingObject: {},
    effectuationObject: {},
},
    {
        id: '2',
        aplId: 'APL-1106',
        aplType: 'Individual',
        aplSubType: '',
        aplIssue: 'Individual Exemption',
        aplStage: 'Adjudication',
        aplLink: 'adjudication',
        aplStatus: 'pending-adjudication',
        aplSubmittedBy: "Appellant",
        adjudDeadline: '2023-12-30T12:49:11.33',
        createdOn: '2022-02-30T12:49:11.33',
        createdBy: 'User Name',
        expedited: true,
        highProfile: true,
        hearingDate: "2023-11-30T12:59:11.33",
        hearingId: "HEARING_ID_02",
        location: 'Appeal Adjudication WB',
        nextActionDate: '2023-10-30T12:50:11.33',
        mdcd: 'true',
        notes: 'notes for ADJ appeal',
        phase: 'no phase',
        phaseChangedDate: "",
        planYear: "2023",
        reopenPhase: "",
        receiptType: "On-line",
        recieptDate: "2022-05-30T12:59:11.33",
        rfiDate: '2024-04-30T12:59:11.33',
        status: 'Pending-Adjudication',
        updatedOn: '',
        updatedBy: '',
        contacts: [
            {
                contactId: "934343e2-c2ab-41ff-a04a-ef8a511807d0",
                appealId: "APL-1106",
                createDateTime: "2022-05-11T11:36:26",
                createOprtr: null,
                creaeOptrName: null,
                updateDateTime: "2022-08-02T15:29:38",
                updateOptr: null,
                updateOprtName: null,
                type: "",
                prsnType: "",
                primaryContact: false,
                sfx: "",
                firstName: "Jane",
                middleName: "John",
                lastName: "Doe",
                emplrName: "",
                dtSgnd: null,
                sgntrInd: false,
                adrSameAsApllant: false,
                authrztn: "",
                ubleToContact: false,
                langAstnc: false,
                spkLang: "",
                wrtnLang: "",
                vrfctnType: "",
                ackAdr: false,
                efctvStrtDt: null,
                efctvEndDt: null,
                authrzgAplntSgtr: false,
                aplntSgndDt: null,
                authrzdRprsntvSgntr: false,
                raprsntvSgndDt: null,
                acAptc: true,
                acMonthlyAmt: 2000,
                acAnnualAmt: 3500,
                acCsr: true,
                acCsrLevel: "true",
                acQhp: false,
                acMdcd: true,
                acChip: true,
                acSep: true,
                acCtstrphc: true,
                acExemption: true,
                acNoAward: true,
                acDisp: "test",
                adacAptc: true,
                adacMonthlyAmt: 123445,
                adacAnnAmount: 1234567,
                adacCsr: true,
                adacCsrLevel: "test1",
                adacQhp: true,
                adacMdcd: true,
                adacChip: true,
                adacSep: true,
                adacCtstrphc: true,
                adacExemp: true,
                adacNoAward: true,
                adacDisp: "djtest1",
                exempEcn: "djtest1",
                exempIndvdlExemp: "test",
                exempBgnDt: "2022-04-13",
                exempEndDt: "2022-04-13",
                exempOutcm: "test",
                exempCmmts: "test",
                pbacAptc: true,
                pbacMonthlyAmt: 123,
                pbacAnnaulAmt: 7456,
                pbacCsr: true,
                pbacCsrLevel: "test",
                pbacPhp: true,
                pbacMdcd: true,
                pbacChip: true,
                pbacSep: true,
                pbacCtstrphc: true,
                pbacExemp: true,
                pbacNoAwd: true,
                pbacDisp: "test",
                ritAnnualIncome: true,
                ritCitizenship: true,
                ritImgrtn: true,
                ritEscMec: true,
                ritNonEscMec: true,
                ritTrbl: true,
                ritMdcd: true,
                sepType: "test",
                sepDnlCrtr: "test",
                sepOutcm: "test",
                sepEfctvDt: "2022-04-12",
                sep: true,
                sepCmmts: "test",
                sepacAptc: true,
                sepacMnthlyAmt: 45634535,
                sepacAnnAmt: 3453678,
                sepacCsr: true,
                sepacCsrLvl: "test",
                sepacQhp: true,
                sepacMdcd: true,
                sepacChip: true,
                sepacSep: true,
                sepacCtstrphc: true,
                sepacExemp: true,
                sepacNoAwd: true,
                sepacDisp: "test",
                ednAptc: true,
                aptcMonthlyAmt: 76684234,
                aptcAnnualAmt: 423245576,
                ednCsr: true,
                ednCsrLevel: "true",
                ednQhp: true,
                ednMedicAid: true,
                ednSep: true,
                ednChip: true,
                ednCstrphc: true,
                ednExempetion: true,
                hicsacAptc: true,
                hicsacMnthlyAmt: 546456,
                hicsacAnnAmt: 55546645646,
                hicsacCsr: true,
                hicsacCsrLvl: "true",
                hicsacQhp: true,
                hicsacMdcd: true,
                hicsacChip: true,
                hicsacSep: true,
                hicsacCtstrphc: true,
                hicsacExemp: true,
                hicsacNoAwd: true,
                hicsacDisp: "test",
                cnstdEdnAptc: true,
                cnstdMonthlyAmt: 45453446,
                cnstdAnnualAmt: 3665643543,
                cnstdEdnCsr: true,
                cnstdEdnCsrLvl: "test",
                cnstdEdnQhp: true,
                cnstdEdnMdcd: true,
                cnstdEdnChip: true,
                cnstdEdnSep: true,
                cnsdtdEdnCtstrphc: true,
                cnstdEdnExemp: true,
                cnstdEdnEcn: "test",
                cnstdEdnDisp: "test",
                cnstdEdnDispDate: "2022-04-12",
                dob: "1986-04-12"
            },
            {
                contactId: "9e7ef627-e09a-4274-906e-8652d0787w12",
                appealId: "APL-1106",
                createDateTime: "2022-05-11T11:28:56",
                createOprtr: null,
                creaeOptrName: null,
                updateDateTime: "2022-08-02T15:29:38",
                updateOptr: null,
                updateOprtName: null,
                type: null,
                prsnType: null,
                primaryContact: false,
                sfx: null,
                firstName: "Second",
                middleName: "M",
                lastName: "Contact",
                emplrName: null,
                dtSgnd: null,
                sgntrInd: false,
                adrSameAsApllant: false,
                authrztn: null,
                ubleToContact: false,
                langAstnc: false,
                spkLang: null,
                wrtnLang: null,
                vrfctnType: null,
                ackAdr: false,
                efctvStrtDt: null,
                efctvEndDt: null,
                authrzgAplntSgtr: false,
                aplntSgndDt: null,
                authrzdRprsntvSgntr: false,
                raprsntvSgndDt: null,
                acAptc: true,
                acMonthlyAmt: 2000,
                acAnnualAmt: 3500,
                acCsr: true,
                acCsrLevel: "true",
                acQhp: false,
                acMdcd: true,
                acChip: true,
                acSep: true,
                acCtstrphc: true,
                acExemption: true,
                acNoAward: true,
                acDisp: "test",
                adacAptc: true,
                adacMonthlyAmt: 123445,
                adacAnnAmount: 1234567,
                adacCsr: true,
                adacCsrLevel: "test1",
                adacQhp: true,
                adacMdcd: true,
                adacChip: true,
                adacSep: true,
                adacCtstrphc: true,
                adacExemp: true,
                adacNoAward: true,
                adacDisp: "djtest1",
                exempEcn: "djtest1",
                exempIndvdlExemp: "test",
                exempBgnDt: "2022-04-13",
                exempEndDt: "2022-04-13",
                exempOutcm: "test2",
                exempCmmts: "test2",
                pbacAptc: true,
                pbacMonthlyAmt: 123,
                pbacAnnaulAmt: 7456,
                pbacCsr: true,
                pbacCsrLevel: "test2",
                pbacPhp: true,
                pbacMdcd: true,
                pbacChip: true,
                pbacSep: true,
                pbacCtstrphc: true,
                pbacExemp: true,
                pbacNoAwd: true,
                pbacDisp: "test2",
                ritAnnualIncome: true,
                ritCitizenship: true,
                ritImgrtn: true,
                ritEscMec: true,
                ritNonEscMec: true,
                ritTrbl: true,
                ritMdcd: true,
                sepType: "test2",
                sepDnlCrtr: "test2",
                sepOutcm: "test2",
                sepEfctvDt: "2022-08-02T15:29:38",
                sep: true,
                sepCmmts: "test",
                sepacAptc: true,
                sepacMnthlyAmt: 45634535,
                sepacAnnAmt: 3453678,
                sepacCsr: true,
                sepacCsrLvl: "test",
                sepacQhp: true,
                sepacMdcd: true,
                sepacChip: true,
                sepacSep: true,
                sepacCtstrphc: true,
                sepacExemp: true,
                sepacNoAwd: true,
                sepacDisp: "test",
                ednAptc: true,
                aptcMonthlyAmt: 76684234,
                aptcAnnualAmt: 423245576,
                ednCsr: true,
                ednCsrLevel: "true",
                ednQhp: true,
                ednMedicAid: true,
                ednSep: true,
                ednChip: true,
                ednCstrphc: true,
                ednExempetion: true,
                hicsacAptc: true,
                hicsacMnthlyAmt: 546456,
                hicsacAnnAmt: 55546645646,
                hicsacCsr: true,
                hicsacCsrLvl: "true",
                hicsacQhp: true,
                hicsacMdcd: true,
                hicsacChip: true,
                hicsacSep: true,
                hicsacCtstrphc: true,
                hicsacExemp: true,
                hicsacNoAwd: true,
                hicsacDisp: "test",
                cnstdEdnAptc: true,
                cnstdMonthlyAmt: 45453446,
                cnstdAnnualAmt: 3665643543,
                cnstdEdnCsr: true,
                cnstdEdnCsrLvl: "test2",
                cnstdEdnQhp: true,
                cnstdEdnMdcd: true,
                cnstdEdnChip: true,
                cnstdEdnSep: true,
                cnsdtdEdnCtstrphc: true,
                cnstdEdnExemp: true,
                cnstdEdnEcn: "test2",
                cnstdEdnDisp: "test2",
                cnstdEdnDispDate: "2022-09-03T15:29:38",
                dob: "1972-10-10T15:29:38"
            }
        ],
        intakeObject: {
            accommFlag: false,
            accommReq: [],
            ackNotice: "",
            ackNoticeDate: "",
            ackNoticeGranted: "",
            appCallReleaseHold: false,
            appReasonForAppeal: "",
            decisionDate: "",
            eacmsRecievedDate: "2022-04-30T12:59:11.33",
            eligDecision: "",
            expComments: "My TestingComments",
            expFlag: true,
            expFor: "Expidite",
            expReqGranted: true,
            formType: "Assessment State",
            intakeType: "Return Mail",
            langAssitComments: "",
            langAssitFlag: false,
            languageAssistReq: [{}],
            mktplcDecision: "",
            ndEndDate: "2022-04-30T12:59:11.33",
            ndFlag: true,
            ndName: "My Testing",
            ndStartDate: "2022-04-30T12:59:11.33",
            openStatusDate: "2022-04-30T12:59:11.33",
            pendedReason: "Disaster Extension ",
            pendedReqEndDate: "2022-04-30T12:59:11.332",
            pendedReqStartDate: "2022-04-12T12:59:11.332",
            smah: false,
            state: "",
            stateModel: "SBM",
            xReference: "Some Value",
            xReferenceType: "Appellant on another appeal"
        },
        adjudicationObject: {
            ackmtNtcMailedDate: "2022-04-12",
            acsTaxData: true,
            actnNtcSentDt: null,
            actnneedatcall: "test",
            actnneedbyeaos: "test",
            actntakendt: "2022-04-12",
            adjEffId: "e2fccd15-3e39-4a88-b1d1-96cd50f368cf",
            adjEffInfo: [],
            adjKpiAfourPbDate: "2022-04-12",
            adjKpiAoneDate: "2022-04-12",
            adjKpiAtwoDate: "2022-04-12",
            adjPhase: "test1",
            adjRFIResDates: [],
            afrdbltyPctg: 789,
            aplDcsnDate: "2022-04-12",
            aplInprogNtcSentDt: null,
            aplclsfctndt: null,
            aplfileddt: "2022-04-12",
            aplrcvdmmsdt: "2022-04-12",
            benchMark: true,
            busnsName: "test",
            clsrdt: "2022-04-12",
            cnstdEDNDate: "2022-04-12",
            cnstdEdnApplcnDate: "2022-04-12",
            cnstdEdnAtstdIncome: 535345345345,
            cnstdEdnComments: "test",
            cnstdEdnFplPctg: 345345345345,
            cntstdEdnOutcome: "test",
            createOperator: "DJtest",
            eactCompletedBy: "DJ1",
            eactCompletedDate: "2022-07-14",
            ednAplcnDate: "2022-04-12",
            ednAtstdIncome: 5433453,
            ednComments: "test",
            ednDate: "2022-04-22",
            ednFplPctg: 45654757,
            efctvRqstdDate: "2022-04-12",
            effPhase: "test1",
            escMec: true,
            escMecAfrdblty: "test",
            escMecType: "test",
            evaltnGrntdDate: null,
            evaltnOutcome: null,
            exempComments: "test1",
            exempDocsRequested: "test1",
            exempRequestNumber: 12345,
            exmpPhase: "test1",
            extensionDate: "2022-04-12",
            fairlRcncl: true,
            ftrToolDueDate: "2022-04-12",
            heargdcsndt: "2022-04-12",
            hicsInfo: [],
            hicsMatchAd: true,
            houseHoldIncome: 456,
            icoAtstdIncome: 97793247923,
            id: "02",
            inconsDocuments: [],
            inconsDtls: [],
            inconsResolvedFfm: "test",
            irCicDate: "2022-04-12",
            irCicPerformed: "test",
            irNtcRespDueDt: null,
            irNtcSent: null,
            irNtcStsf: null,
            irNtcStsfDt: null,
            irntcexprtndt: "2022-04-12",
            irntcsentdt: "2022-04-12",
            iroAdrdbltyPctg: "test",
            iroFplPctg: 42424242342342,
            irresprcvddt: "2022-04-12",
            lowstSlfPlanCost: 56565656,
            marFilingSeparately: true,
            marketPlaceAplcnId: null,
            mdcdorchipdnl: null,
            mdcdorchiptrmntn: null,
            mdcdorchipunwinding: null,
            moenDate: "2022-04-12",
            noFinclAstnc: true,
            noRetroactGrntd: false,
            nonEscMec: true,
            nonEscMecType: "test",
            nonTaxFiler: true,
            outcomeWithThreshhold: "test",
            outstandingDocuments: [],
            overFourHundred: true,
            particagree: "test",
            pbEvaluation: [],
            pendBnftComments: "test",
            pendBnftEfctvDate: "2022-04-12",
            pendBnftElgbl: true,
            pendBnftRqstDate: "2022-04-12",
            pendBnftTrmntnDate: "2022-04-12",
            postIRMatchIR: true,
            postIrNtcSent: null,
            postIrNtcSentDt: null,
            postirdt: "2022-04-12",
            premiumAmount: 123,
            priorEnrlmntHstry: null,
            priorIncons: null,
            rdtrmntn: null,
            retroActGrntd: "test1",
            retroActGrntdDate: "2022-04-12",
            retroActRqstdDate: "2022-04-12",
            retroactElgblDt: null,
            retroactRqstd: "test1",
            rfiRespRecvdDt: null,
            rfiResponseDueDt: null,
            rfiSentDate: null,
            rspnsKpiAtwoDate: "2022-04-12",
            rvsdIrDt: null,
            rvsdirelgbl: "test",
            rvsdirenddt: "2022-04-12",
            rvsdiroutcm: "test",
            rvsdirrsn: "test",
            rvsdirrspns: "test",
            rvsdirstartdt: "2022-04-12",
            schdlheargdt: "2022-04-12",
            schdlheargsentdt: "2022-04-12",
            secondIrElgbl: null,
            sepEndDt: null,
            sepExprtnDate: "2022-04-12",
            sepGrntd: null,
            sepMatchAd: true,
            sepOpenDt: null,
            sercoEfctatnDt: null,
            spclNtcGrp: true,
            timely: null,
            tolrsn: "test",
            tolstartdt: "2022-04-12",
            tolstopdt: "2022-04-12",
            underOneHundFpl: true,
            updateOperator: "test1",
            verificationTools: [],
        },
        hearingObject: {},
        effectuationObject: {},
    }
]


// const INTAKE_OBJ_ARR = [
//     {
//         id: '222',
//         notes: 'Notes Prop',
//         rfiDate: 'RTF Date',
//         nextActionDate: '11/23/22',
//         expedited: "Expidite",
//         highProfile: 'High Profile Type One',
//         aplStatus: 'new',
//         aplStage: 'Intake',
//         aplLink: 'intake',
//         aplId: "APL-51",
//         aplType: "Large Employer",
//         aplSubType: "CHIP",
//         aplIssue: "Individual Exemption",
//         status: "New",
//         location: "Appeal Intake WB",
//         phase: "NO DATA",
//         phaseChangedDate: "",
//         reopenPhase: "",
//         langAssitFlag: false,
//         accommFlag: false,
//         mdcd: true,
//         smah: false,
//         appCallReleaseHold: false,
//         stateModel: "SBM",
//         state: "",
//         intakeType: "Return Mail",
//         formType: "Assessment State",
//         receiptType: "On-line",
//         aplSubmittedBy: "Appellant",
//         pendedReason: "Disaster Extension ",
//         pendedReqStartDate: "2022-04-12T12:59:11.332",
//         pendedReqEndDate: "2022-04-30T12:59:11.332",
//         xReference: "Some Value",
//         xReferenceType: "Appellant on another appeal",
//         recieptDate: "2022-04-30T12:59:11.33",
//         hearingDate: "2022-04-30T12:59:11.33",
//         planYear: "2022",
//         eacmsRecievedDate: "2022-04-30T12:59:11.33",
//         openStatusDate: "2022-04-30T12:59:11.33",
//         adjudDeadline: "No Data",
//         ndFlag: true,
//         ndStartDate: "2022-04-30T12:59:11.33",
//         ndEndDate: "2022-04-30T12:59:11.33",
//         ndName: "My Testing",
//         expFlag: true,
//         expFor: "Expidite",
//         expReqGranted: true,
//         expComments: "My TestingComments",
//         langAssitComments: "",
//         eligDecision: "",
//         decisionDate: "",
//         mktplcDecision: "",
//         appReasonForAppeal: "",
//         ackNotice: "",
//         ackNoticeDate: "",
//         ackNoticeGranted: "",
//         hearingId: "",
//         createdOn: "2022-04-12T12:59:11.332",
//         updatedOn: "2022-04-12T12:59:11.332",
//         contacts: [
//             {
//                 sfx: "",
//                 firstName: "Jane",
//                 middleName: "T",
//                 lastName: "Fernandes",
//                 createDateTime: "",
//                 updateDateTime: "",
//                 type: "type???",
//                 prsnType: "person type??",
//                 primaryContact: "true",
//                 dob: "01/01/1991",
//                 emplrName: "",
//                 dtSgnd: "",
//                 sgntrInd: "",
//                 adrSameAsApllant: "",
//                 authrztn: "",
//                 ubleToContact: "",
//                 langAstnc: "",
//                 spkLang: "",
//                 wrtnLang: "",
//                 vrfctnType: "",
//                 ackAdr: "",
//                 efctvStrtDt: "",
//                 efctvEndDt: "",
//                 authrzgAplntSgtr: "",
//                 aplntSgndDt: "",
//                 authrzdRprsntvSgntr: "",
//                 aprsntvSgndDt: "",
//                 contactAddress: [
//                     {
//                         createDtTime: "",
//                         updateDateTime: "",
//                         type: "Mailing",
//                         street_line: "111 Main St",
//                         secondary: "apt. 101",
//                         city: "Madison",
//                         state: "WI",
//                         zipcode: "01899",
//                         county: "",
//                         country: "USA"
//                     }
//                 ],
//                 contactEmail: [
//                     {
//                         createDtTime: "",
//                         updateDateTime: "",
//                         emailPrefn: "",
//                         emailType: "home",
//                         email: "my@email.com"
//                     }
//                 ],
//                 contactTellInfo: [
//                     {
//                         createDtTime: "",
//                         updateDateTime: "",
//                         txtPrefnc: "",
//                         phone: "12312211232",
//                         phoneType: "home",
//                         extNo: ""
//                     }
//                 ]
//             }
//         ],
//         accommReq: [
//             {
//                 createDataTime: "2022-04-12T12:59:11.332",
//                 updateDateTime: "2022-04-12T12:59:11.332",
//                 personType: "TESTApp",
//                 largPrint: false,
//                 audio: false,
//                 braille: false,
//                 vrs: false,
//                 tty: false,
//                 other: false,
//                 reportable: false,
//                 comments: "Comments"
//             }
//         ],
//         languageAssistReq: [
//             {
//                 createDataTime: "2022-04-12T12:59:11.332",
//                 updateDateTime: "2022-04-12T12:59:11.332",
//                 personType: "Appellant",
//                 spokenLanguage: "Span",
//                 writtenLanguage: "Span",
//                 requestDate: "2022-04-13T12:59:11.332"
//             }
//         ]
//     }
// ]

// function sortObj(obj) {
//     return Object.keys(obj).sort().reduce(function (result, key) {
//         result[key] = obj[key];
//         return result;
//     }, {});
// }

// let maxSpeed = {
//     car: 300,
//     bike: 60,
//     motorbike: 200,
//     airplane: 1000,
//     helicopter: 400,
//     rocket: 8 * 60 * 60
// };
// let sortable = [];
// for (var vehicle in maxSpeed) {
//     sortable.push([vehicle, maxSpeed[vehicle]]);
// }
//
// sortable.sort(function(a, b) {
//     return a[1] - b[1];
// }

// const INTAKE_OBJ_FORMAT = {
//     accommFlag: false,
//     accommReq: [],
//     ackNotice: "",
//     ackNoticeDate: "",
//     ackNoticeGranted: "",
//     adjudDeadline: "No Data",
//     aplId: "APL-51",
//     aplIssue: "Individual Exemption",
//     aplLink: "intake",
//     aplStage: "Intake",
//     aplStatus: "new",
//     aplSubType: "CHIP",
//     aplSubmittedBy: "Appellant",
//     aplType: "Large Employer",
//     appCallReleaseHold: false,
//     appReasonForAppeal: "",
//     contacts: [],
//     createdOn: "2022-04-12T12:59:11.332",
//     decisionDate: "",
//     eacmsRecievedDate: "2022-04-30T12:59:11.33",
//     eligDecision: "",
//     expComments: "My TestingComments",
//     expFlag: true,
//     expFor: "Expidite",
//     expReqGranted: true,
//     expedited: "Expidite",
//     formType: "Assessment State",
//     hearingDate: "2022-04-30T12:59:11.33",
//     hearingId: "",
//     highProfile: "High Profile Type One",
//     id: "222",
//     intakeType: "Return Mail",
//     langAssitComments: "",
//     langAssitFlag: false,
//     languageAssistReq: [{}],
//     location: "Appeal Intake WB",
//     mdcd: true,
//     mktplcDecision: "",
//     ndEndDate: "2022-04-30T12:59:11.33",
//     ndFlag: true,
//     ndName: "My Testing",
//     ndStartDate: "2022-04-30T12:59:11.33",
//     nextActionDate: "11/23/22",
//     notes: "Notes Prop",
//     openStatusDate: "2022-04-30T12:59:11.33",
//     pendedReason: "Disaster Extension ",
//     pendedReqEndDate: "2022-04-30T12:59:11.332",
//     pendedReqStartDate: "2022-04-12T12:59:11.332",
//     phase: "NO DATA",
//     phaseChangedDate: "",
//     planYear: "2022",
//     receiptType: "On-line",
//     recieptDate: "2022-04-30T12:59:11.33",
//     reopenPhase: "",
//     rfiDate: "RTF Date",
//     smah: false,
//     state: "",
//     stateModel: "SBM",
//     status: "New",
//     updatedOn: "2022-04-12T12:59:11.332",
//     xReference: "Some Value",
//     xReferenceType: "Appellant on another appeal"
// }

// const ADJUD_OBJ_FORMAT = {
//     ackmtNtcMailedDate: "2022-04-12",
//     acsTaxData: true,
//     actnNtcSentDt: null,
//     actnneedatcall: "test",
//     actnneedbyeaos: "test",
//     actntakendt: "2022-04-12",
//     adjEffId: "e2fccd15-3e39-4a88-b1d1-96cd50f368cf",
//     adjEffInfo: [],
//     adjKpiAfourPbDate: "2022-04-12",
//     adjKpiAoneDate: "2022-04-12",
//     adjKpiAtwoDate: "2022-04-12",
//     adjPhase: "test1",
//     adjRFIResDates: [],
//     afrdbltyPctg: 789,
//     aplDcsnDate: "2022-04-12",
//     aplId: "APL-1106",
//     aplInprogNtcSentDt: null,
//     aplLink: "adjudication",
//     aplStage: "Adjudication",
//     aplStatus: "Pending Adjudication",
//     aplclsfctndt: null,
//     aplfileddt: "2022-04-12",
//     aplrcvdmmsdt: "2022-04-12",
//     benchMark: true,
//     busnsName: "test",
//     clsrdt: "2022-04-12",
//     cnstdEDNDate: "2022-04-12",
//     cnstdEdnApplcnDate: "2022-04-12",
//     cnstdEdnAtstdIncome: 535345345345,
//     cnstdEdnComments: "test",
//     cnstdEdnFplPctg: 345345345345,
//     cntstdEdnOutcome: "test",
//     createOperator: "DJtest",
//     createOperatorName: "test",
//     createdOn: "2022-07-18T14:19:31",
//     eactCompletedBy: "DJ1",
//     eactCompletedDate: "2022-07-14",
//     ednAplcnDate: "2022-04-12",
//     ednAtstdIncome: 5433453,
//     ednComments: "test",
//     ednDate: "2022-04-22",
//     ednFplPctg: 45654757,
//     efctvRqstdDate: "2022-04-12",
//     effPhase: "test1",
//     escMec: true,
//     escMecAfrdblty: "test",
//     escMecType: "test",
//     evaltnGrntdDate: null,
//     evaltnOutcome: null,
//     exempComments: "test1",
//     exempDocsRequested: "test1",
//     exempRequestNumber: 12345,
//     exmpPhase: "test1",
//     extensionDate: "2022-04-12",
//     fairlRcncl: true,
//     ftrToolDueDate: "2022-04-12",
//     heargdcsndt: "2022-04-12",
//     hicsInfo: [],
//     hicsMatchAd: true,
//     highProfile: "test1",
//     houseHoldIncome: 456,
//     icoAtstdIncome: 97793247923,
//     id: "02",
//     inconsDocuments: [],
//     inconsDtls: [],
//     inconsResolvedFfm: "test",
//     irCicDate: "2022-04-12",
//     irCicPerformed: "test",
//     irNtcRespDueDt: null,
//     irNtcSent: null,
//     irNtcStsf: null,
//     irNtcStsfDt: null,
//     irntcexprtndt: "2022-04-12",
//     irntcsentdt: "2022-04-12",
//     iroAdrdbltyPctg: "test",
//     iroFplPctg: 42424242342342,
//     irresprcvddt: "2022-04-12",
//     lowstSlfPlanCost: 56565656,
//     marFilingSeparately: true,
//     marketPlaceAplcnId: null,
//     mdcdGap: true,
//     mdcdorchipdnl: null,
//     mdcdorchiptrmntn: null,
//     mdcdorchipunwinding: null,
//     moenDate: "2022-04-12",
//     nextActionDate: "2022-04-12",
//     noFinclAstnc: true,
//     noRetroactGrntd: false,
//     nonEscMec: true,
//     nonEscMecType: "test",
//     nonTaxFiler: true,
//     notes: "Notes Prop ion Adjud",
//     outcomeWithThreshhold: "test",
//     outstandingDocuments: [],
//     overFourHundred: true,
//     particagree: "test",
//     pbEvaluation: [],
//     pendBnftComments: "test",
//     pendBnftEfctvDate: "2022-04-12",
//     pendBnftElgbl: true,
//     pendBnftRqstDate: "2022-04-12",
//     pendBnftTrmntnDate: "2022-04-12",
//     postIRMatchIR: true,
//     postIrNtcSent: null,
//     postIrNtcSentDt: null,
//     postirdt: "2022-04-12",
//     premiumAmount: 123,
//     priorEnrlmntHstry: null,
//     priorIncons: null,
//     rdtrmntn: null,
//     retroActGrntd: "test1",
//     retroActGrntdDate: "2022-04-12",
//     retroActRqstdDate: "2022-04-12",
//     retroactElgblDt: null,
//     retroactRqstd: "test1",
//     rfiDate: "3/12/21",
//     rfiRespRecvdDt: null,
//     rfiResponseDueDt: null,
//     rfiSentDate: null,
//     rspnsKpiAtwoDate: "2022-04-12",
//     rvsdIrDt: null,
//     rvsdirelgbl: "test",
//     rvsdirenddt: "2022-04-12",
//     rvsdiroutcm: "test",
//     rvsdirrsn: "test",
//     rvsdirrspns: "test",
//     rvsdirstartdt: "2022-04-12",
//     schdlheargdt: "2022-04-12",
//     schdlheargsentdt: "2022-04-12",
//     secondIrElgbl: null,
//     sepEndDt: null,
//     sepExprtnDate: "2022-04-12",
//     sepGrntd: null,
//     sepMatchAd: true,
//     sepOpenDt: null,
//     sercoEfctatnDt: null,
//     spclNtcGrp: true,
//     timely: null,
//     tolrsn: "test",
//     tolstartdt: "2022-04-12",
//     tolstopdt: "2022-04-12",
//     underOneHundFpl: true,
//     updateOperator: "test1",
//     updateOperatorName: "test1",
//     updatedOn: "2022-08-02T15:29:38",
//     verificationTools: [],
// }

