const INTAKE_OBJ_ARR = [
    {
        id: '222',
        notes: 'Notes Prop',
        rfiDate: 'RTF Date',
        nextActionDate: '11/23/22',
        expedited: "Expidite",
        highProfile: 'High Profile Type One',
        aplStatus: 'new',
        aplStage: 'Intake',
        aplLink: 'intake',
        aplId: "APL-51",
        aplType: "Large Employer",
        aplSubType: "CHIP",
        aplIssue: "Individual Exemption",
        status: "New",
        location: "Appeal Intake WB",
        phase: "NO DATA",
        phaseChangedDate: "",
        reopenPhase: "",
        langAssitFlag: false,
        accommFlag: false,
        mdcd: true,
        smah: false,
        appCallReleaseHold: false,
        stateModel: "SBM",
        state: "",
        intakeType: "Return Mail",
        formType: "Assessment State",
        receiptType: "On-line",
        aplSubmittedBy: "Appellant",
        pendedReason: "Disaster Extension ",
        pendedReqStartDate: "2022-04-12T12:59:11.332",
        pendedReqEndDate: "2022-04-30T12:59:11.332",
        xReference: "Some Value",
        xReferenceType: "Appellant on another appeal",
        recieptDate: "2022-04-30T12:59:11.33",
        hearingDate: "2022-04-30T12:59:11.33",
        planYear: "2022",
        eacmsRecievedDate: "2022-04-30T12:59:11.33",
        openStatusDate: "2022-04-30T12:59:11.33",
        adjudDeadline: "No Data",
        ndFlag: true,
        ndStartDate: "2022-04-30T12:59:11.33",
        ndEndDate: "2022-04-30T12:59:11.33",
        ndName: "My Testing",
        expFlag: true,
        expFor: "Expidite",
        expReqGranted: true,
        expComments: "My TestingComments",
        langAssitComments: "",
        eligDecision: "",
        decisionDate: "",
        mktplcDecision: "",
        appReasonForAppeal: "",
        ackNotice: "",
        ackNoticeDate: "",
        ackNoticeGranted: "",
        hearingId: "",
        createdOn: "2022-04-12T12:59:11.332",
        updatedOn: "2022-04-12T12:59:11.332",
        contacts: [
            {
                sfx: "",
                firstName: "Jane",
                middleName: "T",
                lastName: "Fernandes",
                createDateTime: "",
                updateDateTime: "",
                type: "type???",
                prsnType: "person type??",
                primaryContact: "true",
                dob: "01/01/1991",
                emplrName: "",
                dtSgnd: "",
                sgntrInd: "",
                adrSameAsApllant: "",
                authrztn: "",
                ubleToContact: "",
                langAstnc: "",
                spkLang: "",
                wrtnLang: "",
                vrfctnType: "",
                ackAdr: "",
                efctvStrtDt: "",
                efctvEndDt: "",
                authrzgAplntSgtr: "",
                aplntSgndDt: "",
                authrzdRprsntvSgntr: "",
                aprsntvSgndDt: "",
                contactAddress: [
                    {
                        createDtTime: "",
                        updateDateTime: "",
                        type: "Mailing",
                        street_line: "111 Main St",
                        secondary: "apt. 101",
                        city: "Madison",
                        state: "WI",
                        zipcode: "01899",
                        county: "",
                        country: "USA"
                    }
                ],
                contactEmail: [
                    {
                        createDtTime: "",
                        updateDateTime: "",
                        emailPrefn: "",
                        emailType: "home",
                        email: "my@email.com"
                    }
                ],
                contactTellInfo: [
                    {
                        createDtTime: "",
                        updateDateTime: "",
                        txtPrefnc: "",
                        phone: "12312211232",
                        phoneType: "home",
                        extNo: ""
                    }
                ]
            }
        ],
        accommReq: [
            {
                createDataTime: "2022-04-12T12:59:11.332",
                updateDateTime: "2022-04-12T12:59:11.332",
                personType: "TESTApp",
                largPrint: false,
                audio: false,
                braille: false,
                vrs: false,
                tty: false,
                other: false,
                reportable: false,
                comments: "Comments"
            }
        ],
        languageAssistReq: [
            {
                createDataTime: "2022-04-12T12:59:11.332",
                updateDateTime: "2022-04-12T12:59:11.332",
                personType: "Appellant",
                spokenLanguage: "Span",
                writtenLanguage: "Span",
                requestDate: "2022-04-13T12:59:11.332"
            }
        ]
    }
]

// function sortObj(obj) {
//     return Object.keys(obj).sort().reduce(function (result, key) {
//         result[key] = obj[key];
//         return result;
//     }, {});
// }

let maxSpeed = {
    car: 300,
    bike: 60,
    motorbike: 200,
    airplane: 1000,
    helicopter: 400,
    rocket: 8 * 60 * 60
};
let sortable = [];
// for (var vehicle in maxSpeed) {
//     sortable.push([vehicle, maxSpeed[vehicle]]);
// }
//
// sortable.sort(function(a, b) {
//     return a[1] - b[1];
// }

const INTAKE_OBJ_FORMAT = {
    accommFlag: false,
    accommReq: [],
    ackNotice: "",
    ackNoticeDate: "",
    ackNoticeGranted: "",
    adjudDeadline: "No Data",
    aplId: "APL-51",
    aplIssue: "Individual Exemption",
    aplLink: "intake",
    aplStage: "Intake",
    aplStatus: "new",
    aplSubType: "CHIP",
    aplSubmittedBy: "Appellant",
    aplType: "Large Employer",
    appCallReleaseHold: false,
    appReasonForAppeal: "",
    contacts: [],
    createdOn: "2022-04-12T12:59:11.332",
    decisionDate: "",
    eacmsRecievedDate: "2022-04-30T12:59:11.33",
    eligDecision: "",
    expComments: "My TestingComments",
    expFlag: true,
    expFor: "Expidite",
    expReqGranted: true,
    expedited: "Expidite",
    formType: "Assessment State",
    hearingDate: "2022-04-30T12:59:11.33",
    hearingId: "",
    highProfile: "High Profile Type One",
    id: "222",
    intakeType: "Return Mail",
    langAssitComments: "",
    langAssitFlag: false,
    languageAssistReq: [{}],
    location: "Appeal Intake WB",
    mdcd: true,
    mktplcDecision: "",
    ndEndDate: "2022-04-30T12:59:11.33",
    ndFlag: true,
    ndName: "My Testing",
    ndStartDate: "2022-04-30T12:59:11.33",
    nextActionDate: "11/23/22",
    notes: "Notes Prop",
    openStatusDate: "2022-04-30T12:59:11.33",
    pendedReason: "Disaster Extension ",
    pendedReqEndDate: "2022-04-30T12:59:11.332",
    pendedReqStartDate: "2022-04-12T12:59:11.332",
    phase: "NO DATA",
    phaseChangedDate: "",
    planYear: "2022",
    receiptType: "On-line",
    recieptDate: "2022-04-30T12:59:11.33",
    reopenPhase: "",
    rfiDate: "RTF Date",
    smah: false,
    state: "",
    stateModel: "SBM",
    status: "New",
    updatedOn: "2022-04-12T12:59:11.332",
    xReference: "Some Value",
    xReferenceType: "Appellant on another appeal"
}

const ADJUD_OBJ_FORMAT = {
    ackmtNtcMailedDate: "2022-04-12",
    acsTaxData: true,
    actnNtcSentDt: null,
    actnneedatcall: "test",
    actnneedbyeaos: "test",
    actntakendt: "2022-04-12",
    adjEffId: "e2fccd15-3e39-4a88-b1d1-96cd50f368cf",
    adjEffInfo: [],
    adjKpiAfourPbDate: "2022-04-12",
    adjKpiAoneDate: "2022-04-12",
    adjKpiAtwoDate: "2022-04-12",
    adjPhase: "test1",
    adjRFIResDates: [],
    afrdbltyPctg: 789,
    aplDcsnDate: "2022-04-12",
    aplId: "APL-1106",
    aplInprogNtcSentDt: null,
    aplLink: "adjudication",
    aplStage: "Adjudication",
    aplStatus: "Pending Adjudication",
    aplclsfctndt: null,
    aplfileddt: "2022-04-12",
    aplrcvdmmsdt: "2022-04-12",
    benchMark: true,
    busnsName: "test",
    clsrdt: "2022-04-12",
    cnstdEDNDate: "2022-04-12",
    cnstdEdnApplcnDate: "2022-04-12",
    cnstdEdnAtstdIncome: 535345345345,
    cnstdEdnComments: "test",
    cnstdEdnFplPctg: 345345345345,
    cntstdEdnOutcome: "test",
    createOperator: "DJtest",
    createOperatorName: "test",
    createdOn: "2022-07-18T14:19:31",
    eactCompletedBy: "DJ1",
    eactCompletedDate: "2022-07-14",
    ednAplcnDate: "2022-04-12",
    ednAtstdIncome: 5433453,
    ednComments: "test",
    ednDate: "2022-04-22",
    ednFplPctg: 45654757,
    efctvRqstdDate: "2022-04-12",
    effPhase: "test1",
    escMec: true,
    escMecAfrdblty: "test",
    escMecType: "test",
    evaltnGrntdDate: null,
    evaltnOutcome: null,
    exempComments: "test1",
    exempDocsRequested: "test1",
    exempRequestNumber: 12345,
    exmpPhase: "test1",
    extensionDate: "2022-04-12",
    fairlRcncl: true,
    ftrToolDueDate: "2022-04-12",
    heargdcsndt: "2022-04-12",
    hicsInfo: [],
    hicsMatchAd: true,
    highProfile: "test1",
    houseHoldIncome: 456,
    icoAtstdIncome: 97793247923,
    id: "02",
    inconsDocuments: [],
    inconsDtls: [],
    inconsResolvedFfm: "test",
    irCicDate: "2022-04-12",
    irCicPerformed: "test",
    irNtcRespDueDt: null,
    irNtcSent: null,
    irNtcStsf: null,
    irNtcStsfDt: null,
    irntcexprtndt: "2022-04-12",
    irntcsentdt: "2022-04-12",
    iroAdrdbltyPctg: "test",
    iroFplPctg: 42424242342342,
    irresprcvddt: "2022-04-12",
    lowstSlfPlanCost: 56565656,
    marFilingSeparately: true,
    marketPlaceAplcnId: null,
    mdcdGap: true,
    mdcdorchipdnl: null,
    mdcdorchiptrmntn: null,
    mdcdorchipunwinding: null,
    moenDate: "2022-04-12",
    nextActionDate: "2022-04-12",
    noFinclAstnc: true,
    noRetroactGrntd: false,
    nonEscMec: true,
    nonEscMecType: "test",
    nonTaxFiler: true,
    notes: "Notes Prop ion Adjud",
    outcomeWithThreshhold: "test",
    outstandingDocuments: [],
    overFourHundred: true,
    particagree: "test",
    pbEvaluation: [],
    pendBnftComments: "test",
    pendBnftEfctvDate: "2022-04-12",
    pendBnftElgbl: true,
    pendBnftRqstDate: "2022-04-12",
    pendBnftTrmntnDate: "2022-04-12",
    postIRMatchIR: true,
    postIrNtcSent: null,
    postIrNtcSentDt: null,
    postirdt: "2022-04-12",
    premiumAmount: 123,
    priorEnrlmntHstry: null,
    priorIncons: null,
    rdtrmntn: null,
    retroActGrntd: "test1",
    retroActGrntdDate: "2022-04-12",
    retroActRqstdDate: "2022-04-12",
    retroactElgblDt: null,
    retroactRqstd: "test1",
    rfiDate: "3/12/21",
    rfiRespRecvdDt: null,
    rfiResponseDueDt: null,
    rfiSentDate: null,
    rspnsKpiAtwoDate: "2022-04-12",
    rvsdIrDt: null,
    rvsdirelgbl: "test",
    rvsdirenddt: "2022-04-12",
    rvsdiroutcm: "test",
    rvsdirrsn: "test",
    rvsdirrspns: "test",
    rvsdirstartdt: "2022-04-12",
    schdlheargdt: "2022-04-12",
    schdlheargsentdt: "2022-04-12",
    secondIrElgbl: null,
    sepEndDt: null,
    sepExprtnDate: "2022-04-12",
    sepGrntd: null,
    sepMatchAd: true,
    sepOpenDt: null,
    sercoEfctatnDt: null,
    spclNtcGrp: true,
    timely: null,
    tolrsn: "test",
    tolstartdt: "2022-04-12",
    tolstopdt: "2022-04-12",
    underOneHundFpl: true,
    updateOperator: "test1",
    updateOperatorName: "test1",
    updatedOn: "2022-08-02T15:29:38",
    verificationTools: [],
}

