// contactId: [''],
//     appealId: [''],
//     prsnType: [''],
//     type: [''],
//     primaryContact: [false],
//     ubleToContact: [false, [Validators.required]],
//     firstName: ['', [Validators.required, Validators.maxLength(this.firstNameMaxLength), Validators.pattern('^[a-zA-Z-]+')]],
//     middleName: ['', [Validators.maxLength(this.lastNameMaxLength), Validators.pattern('^[a-zA-Z-]+')]],
//     lastName: ['', [Validators.required, Validators.maxLength(this.lastNameMaxLength), Validators.pattern('^[a-zA-Z-]+')]],
//     sfx: [''],
//     dob: ['', [CustomValidators.noFutureDate]],
//     sgntrInd: [false],
//     dtSgnd: ['', [CustomValidators.noFutureDate]],
//     adrSameAsApllant: [false],
//     contactTellInfo: new FormControl([]),
//     contactEmail: new FormControl([]),
//     contactAddress: new FormControl([]),