export const MY_APPEALS = [
    {
        id: 1,
        aplId: 'APL-000001',
        aplType: 'IN',
        aplSubType: 'AT',
        createdOn: '',
        expedited: true,
        phase: 'Hold RFI',
        highProfile: 'High Profile Type One',
        updatedOn: '',
        planYear: '2020',
        adjudDeadline: '5/31/20',
        hearingDate: '7/04/21',
        nextActionDate: '11/23/22',
        rfiDate: '3/12/21',
        notes: 'too short for that',
        aplStatus: 'Pending Adjudication',
        aplStage: 'Adjudication',
        aplLink: 'adjudication'
    },
    {
        id: 2,
        aplId: 'APL-000002',
        aplType: 'IN',
        aplSubType: 'ADJ-SUB-1',
        createdOn: '5/30/21',
        expedited: false,
        phase: 'Hold RFI',
        highProfile: 'High Profile Type Two',
        updatedOn: '6/31/22',
        planYear: '2020',
        adjudDeadline: '5/31/20',
        hearingDate: '7/04/21',
        nextActionDate: '11/23/22',
        rfiDate: '3/12/21',
        notes: 'may a link her?',
        aplStatus: 'Open',
        aplStage: 'Intake',
        aplLink: 'intake'
    },
    {
        id: 3,
        aplId: 'APL-000003',
        aplType: 'IN',
        aplSubType: 'Later',
        createdOn: '',
        expedited: true,
        phase: 'Hold RFI',
        highProfile: 'or boolean here?',
        updatedOn: '',
        planYear: '2020',
        adjudDeadline: '5/12/20',
        hearingDate: '7/04/21',
        nextActionDate: '10/23/22',
        rfiDate: '3/12/22',
        notes: 'tsome',
        aplStatus: 'Add Later',
        aplStage: 'Hearing',
        aplLink: 'hearing'
    },
    {
        id: 4,
        aplId: 'APL-000004',
        aplType: 'IN',
        aplSubType: 'EFF-SOON-SUBTYPE',
        createdOn: '',
        expedited: false,
        phase: 'Add later',
        highProfile: 'or boolean here?',
        updatedOn: '',
        planYear: '2020',
        adjudDeadline: '5/12/20',
        hearingDate: '7/04/21',
        nextActionDate: '10/23/22',
        rfiDate: '3/12/22',
        notes: 'some',
        aplStatus: 'Add Later',
        aplStage: 'Effectuation/Closure',
        aplLink: 'closure'
    },
    {
        id: 5,
        aplId: 'APL-000005',
        aplType: 'IN',
        aplSubType: 'Add later',
        createdOn: '4/09/19',
        expedited: false,
        phase: 'Add later',
        highProfile: 'or boolean here?',
        updatedOn: '',
        planYear: '2020',
        adjudDeadline: '5/12/20',
        hearingDate: '7/04/21',
        nextActionDate: '10/23/22',
        rfiDate: '3/12/22',
        notes: 'some',
        aplStatus: 'New',
        aplStage: 'Intake',
        aplLink: 'intake'
    },
    {
        id: 6,
        aplId: 'APL-000006',
        aplType: 'IN',
        aplSubType: 'AT',
        createdOn: '7/11/21',
        expedited: false,
        phase: 'Add later',
        highProfile: 'yes',
        updatedOn: '',
        planYear: '2022',
        adjudDeadline: '8/12/22',
        hearingDate: '9/04/21',
        nextActionDate: '12/23/22',
        rfiDate: '3/22/21',
        notes: 'my notes here for id 6',
        aplStatus: 'Pending-Adjudication',
        aplStage: 'Adjudication',
        aplLink: 'adjudication'
    },
]
