export const PAYLOAD_NEW_APL = [{
    id: '11',
    notes: 'too short for that',
    aplId: "APL-51",
    aplType: "Large Employer ",
    aplSubType: "CHIP",
    aplIssue: "Individual Exemption",
    status: "New",
    location: "Appeal Intake WB",
    phase: "",
    phaseChangedDate: "",
    reopenPhase: "",
    langAssitFlag: false,
    accommFlag: false,
    mdcd: true,
    smah: false,
    appCallReleaseHold: false,
    stateModel: "SBM",
    state: "",
    intakeType: "Return Mail",
    formType: "Assessment State",
    receiptType: "On-line",
    aplSubmittedBy: "Appellant",
    pendedReason: "Disaster Extension ",
    pendedReqStartDate: "2022-04-12T12:59:11.332",
    pendedReqEndDate: "2022-04-30T12:59:11.332",
    xReference: "SOmeValue",
    xReferenceType: "Appellant on another appeal",
    recieptDate: "2022-04-30T12:59:11.33",
    hearingRecieptDate: "2022-04-30T12:59:11.33",
    planYear: "2022",
    eacmsRecievedDate: "2022-04-30T12:59:11.33",
    openStatusDate: "2022-04-30T12:59:11.33",
    adjDeadlineDate: "",
    ndFlag: true,
    ndStartDate: "2022-04-30T12:59:11.33",
    ndEndDate: "2022-04-30T12:59:11.33",
    ndName: "My Testing",
    expFlag: true,
    expFor: "Expidite",
    expReqGranted: true,
    expComments: "My TestingComments",
    langAssitComments: "",
    eligDecision: "",
    decisionDate: "",
    mktplcDecision: "",
    appReasonForAppeal: "",
    ackNotice: "",
    ackNoticeDate: "",
    ackNoticeGranted: "",
    hearingId: "",
    createdOn: "2022-04-12T12:59:11.332",
    updatedOn: "2022-04-12T12:59:11.332",
    aplStatus: 'Pending Adjudication',
    aplStage: 'Adjudication',
    aplLink: 'adjudication',
    contactReq: [
        {
            sfx: "",
            firstName: "TestF",
            middleName: "TestM",
            lastName: "TestL",
            createDateTime: "",
            updateDateTime: "",
            type: "",
            prsnType: "",
            primaryContact: "",
            dob: "",
            emplrName: "",
            dtSgnd: "",
            sgntrInd: "",
            adrSameAsApllant: "",
            authrztn: "",
            ubleToContact: "",
            langAstnc: "",
            spkLang: "",
            wrtnLang: "",
            vrfctnType: "",
            ackAdr: "",
            efctvStrtDt: "",
            efctvEndDt: "",
            authrzgAplntSgtr: "",
            aplntSgndDt: "",
            authrzdRprsntvSgntr: "",
            aprsntvSgndDt: "",
            contactAddress: [],
            contactEmail: [],
            contactTellInfo: []
        }
    ],
    accommReq: [
        {
            createDataTime: "",
            updateDateTime: "",
            personType: "",
            largPrint: null,
            audio: null,
            braille: false,
            vrs: false,
            tty: false,
            other: false,
            reportable: false,
            comments: ""
        }
    ],
    languageAssistReq: [
        {
            createDataTime: "",
            updateDateTime: "",
            personType: "",
            spokenLanguage: "",
            writtenLanguage: "",
            requestDate: ""
        }
    ]
}]
