const A_OBJ = {
    accommFlag: false,
    accommReq: [],
    ackNotice: "",
    ackNoticeDate: "",
    ackNoticeGranted: "",
    adjudDeadline: "No Data",
    aplId: "APL-51",
    aplIssue: "Individual Exemption",
    aplLink: "intake",
    aplStage: "Intake",
    aplStatus: "new",
    aplSubType: "CHIP",
    aplSubmittedBy: "Appellant",
    aplType: "Large Employer",
    appCallReleaseHold: false,
    appReasonForAppeal: "",
    contacts: [],
    createdOn: "2022-04-12T12:59:11.332",
    decisionDate: "",
    eacmsRecievedDate: "2022-04-30T12:59:11.33",
    eligDecision: "",
    expComments: "My TestingComments",
    expFlag: true,
    expFor: "Expidite",
    expReqGranted: true,
    expedited: "Expidite",
    formType: "Assessment State",
    hearingDate: "2022-04-30T12:59:11.33",
    hearingId: "",
    highProfile: "High Profile Type One",
    id: "222",
    intakeType: "Return Mail",
    langAssitComments: "",
    langAssitFlag: false,
    languageAssistReq: [{}],
    location: "Appeal Intake WB",
    mdcd: true,
    mktplcDecision: "",
    ndEndDate: "2022-04-30T12:59:11.33",
    ndFlag: true,
    ndName: "My Testing",
    ndStartDate: "2022-04-30T12:59:11.33",
    nextActionDate: "11/23/22",
    notes: "Notes Prop",
    openStatusDate: "2022-04-30T12:59:11.33",
    pendedReason: "Disaster Extension ",
    pendedReqEndDate: "2022-04-30T12:59:11.332",
    pendedReqStartDate: "2022-04-12T12:59:11.332",
    phase: "NO DATA",
    phaseChangedDate: "",
    planYear: "2022",
    receiptType: "On-line",
    recieptDate: "2022-04-30T12:59:11.33",
    reopenPhase: "",
    rfiDate: "RTF Date",
    smah: false,
    state: "",
    stateModel: "SBM",
    status: "New",
    updatedOn: "2022-04-12T12:59:11.332",
    xReference: "Some Value",
    xReferenceType: "Appellant on another appeal"
}