const APL_CASE_COMMON = {
    id: '1',
    aplId: 'APL_51',
    aplType: 'Large Employer',
    aplSubType: 'CHIP',
    aplIssue: 'Individual Exemption',
    aplStage: 'Intake',
    aplLink: 'intake',
    aplStatus: 'new',
    aplSubmittedBy: "Appellant",
    adjudDeadline: '',
    createdOn: '2022-02-30T12:49:11.33',
    createdBy: 'User Name',
    expedited: true,
    highProfile: 'Boolean or String?',
    hearingDate: "2024-01-30T12:59:11.33",
    hearingId: "HEARING_ID_01",
    location: 'Appeal Intake WB',
    nextActionDate: '2023-12-30T12:50:11.33',
    mdcd: 'true',
    notes: 'notes for APL_51',
    phase: 'phase should be here',
    phaseChangedDate: "",
    planYear: "2024",
    reopenPhase: "",
    receiptType: "On-line",
    recieptDate: "2022-05-30T12:59:11.33",
    rfiDate: '2024-04-30T12:59:11.33',
    status: 'New',
    updatedOn: '',
    updatedBy: '',
    contacts: [
        {
            contactId: "934343e2-c2ab-41ff-a04a-ef8a511807d9",
            appealId: "APL-1106",
            createDateTime: "2022-05-11T11:36:26",
            createOprtr: null,
            creaeOptrName: null,
            updateDateTime: "2022-08-02T15:29:38",
            updateOptr: null,
            updateOprtName: null,
            type: "",
            prsnType: "",
            primaryContact: false,
            sfx: "",
            firstName: "TestF",
            middleName: "TestM",
            lastName: "TestL",
            Dob: "1986-04-12",
            emplrName: "",
            dtSgnd: null,
            sgntrInd: false,
            adrSameAsApllant: false,
            authrztn: "",
            ubleToContact: false,
            langAstnc: false,
            spkLang: "",
            wrtnLang: "",
            vrfctnType: "",
            ackAdr: false,
            efctvStrtDt: null,
            efctvEndDt: null,
            authrzgAplntSgtr: false,
            aplntSgndDt: null,
            authrzdRprsntvSgntr: false,
            raprsntvSgndDt: null,
            acAptc: true,
            acMonthlyAmt: 2000,
            acAnnualAmt: 3500,
            acCsr: true,
            acCsrLevel: "true",
            acQhp: false,
            acMdcd: true,
            acChip: true,
            acSep: true,
            acCtstrphc: true,
            acExemption: true,
            acNoAward: true,
            acDisp: "test",
            adacAptc: true,
            adacMonthlyAmt: 123445,
            adacAnnAmount: 1234567,
            adacCsr: true,
            adacCsrLevel: "test1",
            adacQhp: true,
            adacMdcd: true,
            adacChip: true,
            adacSep: true,
            adacCtstrphc: true,
            adacExemp: true,
            adacNoAward: true,
            adacDisp: "djtest1",
            exempEcn: "djtest1",
            exempIndvdlExemp: "test",
            exempBgnDt: "2022-04-13",
            exempEndDt: "2022-04-13",
            exempOutcm: "test",
            exempCmmts: "test",
            pbacAptc: true,
            pbacMonthlyAmt: 123,
            pbacAnnaulAmt: 7456,
            pbacCsr: true,
            pbacCsrLevel: "test",
            pbacPhp: true,
            pbacMdcd: true,
            pbacChip: true,
            pbacSep: true,
            pbacCtstrphc: true,
            pbacExemp: true,
            pbacNoAwd: true,
            pbacDisp: "test",
            ritAnnualIncome: true,
            ritCitizenship: true,
            ritImgrtn: true,
            ritEscMec: true,
            ritNonEscMec: true,
            ritTrbl: true,
            ritMdcd: true,
            sepType: "test",
            sepDnlCrtr: "test",
            sepOutcm: "test",
            sepEfctvDt: "2022-04-12",
            sep: true,
            sepCmmts: "test",
            sepacAptc: true,
            sepacMnthlyAmt: 45634535,
            sepacAnnAmt: 3453678,
            sepacCsr: true,
            sepacCsrLvl: "test",
            sepacQhp: true,
            sepacMdcd: true,
            sepacChip: true,
            sepacSep: true,
            sepacCtstrphc: true,
            sepacExemp: true,
            sepacNoAwd: true,
            sepacDisp: "test",
            ednAptc: true,
            aptcMonthlyAmt: 76684234,
            aptcAnnualAmt: 423245576,
            ednCsr: true,
            ednCsrLevel: "true",
            ednQhp: true,
            ednMedicAid: true,
            ednSep: true,
            ednChip: true,
            ednCstrphc: true,
            ednExempetion: true,
            hicsacAptc: true,
            hicsacMnthlyAmt: 546456,
            hicsacAnnAmt: 55546645646,
            hicsacCsr: true,
            hicsacCsrLvl: "true",
            hicsacQhp: true,
            hicsacMdcd: true,
            hicsacChip: true,
            hicsacSep: true,
            hicsacCtstrphc: true,
            hicsacExemp: true,
            hicsacNoAwd: true,
            hicsacDisp: "test",
            cnstdEdnAptc: true,
            cnstdMonthlyAmt: 45453446,
            cnstdAnnualAmt: 3665643543,
            cnstdEdnCsr: true,
            cnstdEdnCsrLvl: "test",
            cnstdEdnQhp: true,
            cnstdEdnMdcd: true,
            cnstdEdnChip: true,
            cnstdEdnSep: true,
            cnsdtdEdnCtstrphc: true,
            cnstdEdnExemp: true,
            cnstdEdnEcn: "test",
            cnstdEdnDisp: "test",
            cnstdEdnDispDate: "2022-04-12",
            dob: "1986-04-12"
        },
        {
            contactId: "9e7ef627-e09a-4274-906e-8652d0787d85",
            appealId: "APL-1106",
            createDateTime: "2022-05-11T11:28:56",
            createOprtr: null,
            creaeOptrName: null,
            updateDateTime: "2022-08-02T15:29:38",
            updateOptr: null,
            updateOprtName: null,
            type: null,
            prsnType: null,
            primaryContact: false,
            sfx: null,
            firstName: "TestF",
            middleName: "TestM",
            lastName: "TestL",
            Dob: null,
            emplrName: null,
            dtSgnd: null,
            sgntrInd: false,
            adrSameAsApllant: false,
            authrztn: null,
            ubleToContact: false,
            langAstnc: false,
            spkLang: null,
            wrtnLang: null,
            vrfctnType: null,
            ackAdr: false,
            efctvStrtDt: null,
            efctvEndDt: null,
            authrzgAplntSgtr: false,
            aplntSgndDt: null,
            authrzdRprsntvSgntr: false,
            raprsntvSgndDt: null,
            acAptc: true,
            acMonthlyAmt: 2000,
            acAnnualAmt: 3500,
            acCsr: true,
            acCsrLevel: "true",
            acQhp: false,
            acMdcd: true,
            acChip: true,
            acSep: true,
            acCtstrphc: true,
            acExemption: true,
            acNoAward: true,
            acDisp: "test",
            adacAptc: true,
            adacMonthlyAmt: 123445,
            adacAnnAmount: 1234567,
            adacCsr: true,
            adacCsrLevel: "test1",
            adacQhp: true,
            adacMdcd: true,
            adacChip: true,
            adacSep: true,
            adacCtstrphc: true,
            adacExemp: true,
            adacNoAward: true,
            adacDisp: "djtest1",
            exempEcn: "djtest1",
            exempIndvdlExemp: "test",
            exempBgnDt: "2022-04-13",
            exempEndDt: "2022-04-13",
            exempOutcm: "test",
            exempCmmts: "test",
            pbacAptc: true,
            pbacMonthlyAmt: 123,
            pbacAnnaulAmt: 7456,
            pbacCsr: true,
            pbacCsrLevel: "test",
            pbacPhp: true,
            pbacMdcd: true,
            pbacChip: true,
            pbacSep: true,
            pbacCtstrphc: true,
            pbacExemp: true,
            pbacNoAwd: true,
            pbacDisp: "test",
            ritAnnualIncome: true,
            ritCitizenship: true,
            ritImgrtn: true,
            ritEscMec: true,
            ritNonEscMec: true,
            ritTrbl: true,
            ritMdcd: true,
            sepType: "test",
            sepDnlCrtr: "test",
            sepOutcm: "test",
            sepEfctvDt: "2022-04-12",
            sep: true,
            sepCmmts: "test",
            sepacAptc: true,
            sepacMnthlyAmt: 45634535,
            sepacAnnAmt: 3453678,
            sepacCsr: true,
            sepacCsrLvl: "test",
            sepacQhp: true,
            sepacMdcd: true,
            sepacChip: true,
            sepacSep: true,
            sepacCtstrphc: true,
            sepacExemp: true,
            sepacNoAwd: true,
            sepacDisp: "test",
            ednAptc: true,
            aptcMonthlyAmt: 76684234,
            aptcAnnualAmt: 423245576,
            ednCsr: true,
            ednCsrLevel: "true",
            ednQhp: true,
            ednMedicAid: true,
            ednSep: true,
            ednChip: true,
            ednCstrphc: true,
            ednExempetion: true,
            hicsacAptc: true,
            hicsacMnthlyAmt: 546456,
            hicsacAnnAmt: 55546645646,
            hicsacCsr: true,
            hicsacCsrLvl: "true",
            hicsacQhp: true,
            hicsacMdcd: true,
            hicsacChip: true,
            hicsacSep: true,
            hicsacCtstrphc: true,
            hicsacExemp: true,
            hicsacNoAwd: true,
            hicsacDisp: "test",
            cnstdEdnAptc: true,
            cnstdMonthlyAmt: 45453446,
            cnstdAnnualAmt: 3665643543,
            cnstdEdnCsr: true,
            cnstdEdnCsrLvl: "test",
            cnstdEdnQhp: true,
            cnstdEdnMdcd: true,
            cnstdEdnChip: true,
            cnstdEdnSep: true,
            cnsdtdEdnCtstrphc: true,
            cnstdEdnExemp: true,
            cnstdEdnEcn: "test",
            cnstdEdnDisp: "test",
            cnstdEdnDispDate: "2022-04-12",
            dob: null
        }
    ],
    intakeObject: {
        accommFlag: false,
        accommReq: [],
        ackNotice: "",
        ackNoticeDate: "",
        ackNoticeGranted: "",
        appCallReleaseHold: false,
        appReasonForAppeal: "",
        decisionDate: "",
        eacmsRecievedDate: "2022-04-30T12:59:11.33",
        eligDecision: "",
        expComments: "My TestingComments",
        expFlag: true,
        expFor: "Expidite",
        expReqGranted: true,
        formType: "Assessment State",
        intakeType: "Return Mail",
        langAssitComments: "",
        langAssitFlag: false,
        languageAssistReq: [{}],
        mktplcDecision: "",
        ndEndDate: "2022-04-30T12:59:11.33",
        ndFlag: true,
        ndName: "My Testing",
        ndStartDate: "2022-04-30T12:59:11.33",
        openStatusDate: "2022-04-30T12:59:11.33",
        pendedReason: "Disaster Extension ",
        pendedReqEndDate: "2022-04-30T12:59:11.332",
        pendedReqStartDate: "2022-04-12T12:59:11.332",
        smah: false,
        state: "",
        stateModel: "SBM",
        xReference: "Some Value",
        xReferenceType: "Appellant on another appeal"
    },
    adjudicationObject: {
        ackmtNtcMailedDate: "2022-04-12",
        acsTaxData: true,
        actnNtcSentDt: null,
        actnneedatcall: "test",
        actnneedbyeaos: "test",
        actntakendt: "2022-04-12",
        adjEffId: "e2fccd15-3e39-4a88-b1d1-96cd50f368cf",
        adjEffInfo: [],
        adjKpiAfourPbDate: "2022-04-12",
        adjKpiAoneDate: "2022-04-12",
        adjKpiAtwoDate: "2022-04-12",
        adjPhase: "test1",
        adjRFIResDates: [],
        afrdbltyPctg: 789,
        aplDcsnDate: "2022-04-12",
        aplInprogNtcSentDt: null,
        aplclsfctndt: null,
        aplfileddt: "2022-04-12",
        aplrcvdmmsdt: "2022-04-12",
        benchMark: true,
        busnsName: "test",
        clsrdt: "2022-04-12",
        cnstdEDNDate: "2022-04-12",
        cnstdEdnApplcnDate: "2022-04-12",
        cnstdEdnAtstdIncome: 535345345345,
        cnstdEdnComments: "test",
        cnstdEdnFplPctg: 345345345345,
        cntstdEdnOutcome: "test",
        createOperator: "DJtest",
        eactCompletedBy: "DJ1",
        eactCompletedDate: "2022-07-14",
        ednAplcnDate: "2022-04-12",
        ednAtstdIncome: 5433453,
        ednComments: "test",
        ednDate: "2022-04-22",
        ednFplPctg: 45654757,
        efctvRqstdDate: "2022-04-12",
        effPhase: "test1",
        escMec: true,
        escMecAfrdblty: "test",
        escMecType: "test",
        evaltnGrntdDate: null,
        evaltnOutcome: null,
        exempComments: "test1",
        exempDocsRequested: "test1",
        exempRequestNumber: 12345,
        exmpPhase: "test1",
        extensionDate: "2022-04-12",
        fairlRcncl: true,
        ftrToolDueDate: "2022-04-12",
        heargdcsndt: "2022-04-12",
        hicsInfo: [],
        hicsMatchAd: true,
        houseHoldIncome: 456,
        icoAtstdIncome: 97793247923,
        id: "02",
        inconsDocuments: [],
        inconsDtls: [],
        inconsResolvedFfm: "test",
        irCicDate: "2022-04-12",
        irCicPerformed: "test",
        irNtcRespDueDt: null,
        irNtcSent: null,
        irNtcStsf: null,
        irNtcStsfDt: null,
        irntcexprtndt: "2022-04-12",
        irntcsentdt: "2022-04-12",
        iroAdrdbltyPctg: "test",
        iroFplPctg: 42424242342342,
        irresprcvddt: "2022-04-12",
        lowstSlfPlanCost: 56565656,
        marFilingSeparately: true,
        marketPlaceAplcnId: null,
        mdcdorchipdnl: null,
        mdcdorchiptrmntn: null,
        mdcdorchipunwinding: null,
        moenDate: "2022-04-12",
        noFinclAstnc: true,
        noRetroactGrntd: false,
        nonEscMec: true,
        nonEscMecType: "test",
        nonTaxFiler: true,
        outcomeWithThreshhold: "test",
        outstandingDocuments: [],
        overFourHundred: true,
        particagree: "test",
        pbEvaluation: [],
        pendBnftComments: "test",
        pendBnftEfctvDate: "2022-04-12",
        pendBnftElgbl: true,
        pendBnftRqstDate: "2022-04-12",
        pendBnftTrmntnDate: "2022-04-12",
        postIRMatchIR: true,
        postIrNtcSent: null,
        postIrNtcSentDt: null,
        postirdt: "2022-04-12",
        premiumAmount: 123,
        priorEnrlmntHstry: null,
        priorIncons: null,
        rdtrmntn: null,
        retroActGrntd: "test1",
        retroActGrntdDate: "2022-04-12",
        retroActRqstdDate: "2022-04-12",
        retroactElgblDt: null,
        retroactRqstd: "test1",
        rfiRespRecvdDt: null,
        rfiResponseDueDt: null,
        rfiSentDate: null,
        rspnsKpiAtwoDate: "2022-04-12",
        rvsdIrDt: null,
        rvsdirelgbl: "test",
        rvsdirenddt: "2022-04-12",
        rvsdiroutcm: "test",
        rvsdirrsn: "test",
        rvsdirrspns: "test",
        rvsdirstartdt: "2022-04-12",
        schdlheargdt: "2022-04-12",
        schdlheargsentdt: "2022-04-12",
        secondIrElgbl: null,
        sepEndDt: null,
        sepExprtnDate: "2022-04-12",
        sepGrntd: null,
        sepMatchAd: true,
        sepOpenDt: null,
        sercoEfctatnDt: null,
        spclNtcGrp: true,
        timely: null,
        tolrsn: "test",
        tolstartdt: "2022-04-12",
        tolstopdt: "2022-04-12",
        underOneHundFpl: true,
        updateOperator: "test1",
        verificationTools: [],
    },
    hearingObject: {},
    effectuationObject: {},
}


// const APL_CASE_COMMON_INIT = {
//     id: '',
//     aplId: '',
//     aplType: '',
//     aplSubType: '',
//     aplIssue: '',
//     aplStage: '',
//     aplLink: '',
//     aplStatus: '',
//     adjudDeadline: '',
//     createdOn: '',
//     createdBy: '',
//     updatedOn: '',
//     updatedBy: '',
//     location: '',
//     nextActionDate: '',
//     mdcd: '',
//     notes: '',
//     rfiDate: '',
//     hearingDate: "2022-04-30T12:59:11.33",
//     hearingId: "",
//     contacts: [
//         {
//             contactId: "934343e2-c2ab-41ff-a04a-ef8a511807d9",
//             appealId: "APL-1106",
//             createDateTime: "2022-05-11T11:36:26",
//             createOprtr: null,
//             creaeOptrName: null,
//             updateDateTime: "2022-08-02T15:29:38",
//             updateOptr: null,
//             updateOprtName: null,
//             type: "",
//             prsnType: "",
//             primaryContact: false,
//             sfx: "",
//             firstName: "TestF",
//             middleName: "TestM",
//             lastName: "TestL",
//             Dob: "1986-04-12",
//             emplrName: "",
//             dtSgnd: null,
//             sgntrInd: false,
//             adrSameAsApllant: false,
//             authrztn: "",
//             ubleToContact: false,
//             langAstnc: false,
//             spkLang: "",
//             wrtnLang: "",
//             vrfctnType: "",
//             ackAdr: false,
//             efctvStrtDt: null,
//             efctvEndDt: null,
//             authrzgAplntSgtr: false,
//             aplntSgndDt: null,
//             authrzdRprsntvSgntr: false,
//             raprsntvSgndDt: null,
//             acAptc: true,
//             acMonthlyAmt: 2000,
//             acAnnualAmt: 3500,
//             acCsr: true,
//             acCsrLevel: "true",
//             acQhp: false,
//             acMdcd: true,
//             acChip: true,
//             acSep: true,
//             acCtstrphc: true,
//             acExemption: true,
//             acNoAward: true,
//             acDisp: "test",
//             adacAptc: true,
//             adacMonthlyAmt: 123445,
//             adacAnnAmount: 1234567,
//             adacCsr: true,
//             adacCsrLevel: "test1",
//             adacQhp: true,
//             adacMdcd: true,
//             adacChip: true,
//             adacSep: true,
//             adacCtstrphc: true,
//             adacExemp: true,
//             adacNoAward: true,
//             adacDisp: "djtest1",
//             exempEcn: "djtest1",
//             exempIndvdlExemp: "test",
//             exempBgnDt: "2022-04-13",
//             exempEndDt: "2022-04-13",
//             exempOutcm: "test",
//             exempCmmts: "test",
//             pbacAptc: true,
//             pbacMonthlyAmt: 123,
//             pbacAnnaulAmt: 7456,
//             pbacCsr: true,
//             pbacCsrLevel: "test",
//             pbacPhp: true,
//             pbacMdcd: true,
//             pbacChip: true,
//             pbacSep: true,
//             pbacCtstrphc: true,
//             pbacExemp: true,
//             pbacNoAwd: true,
//             pbacDisp: "test",
//             ritAnnualIncome: true,
//             ritCitizenship: true,
//             ritImgrtn: true,
//             ritEscMec: true,
//             ritNonEscMec: true,
//             ritTrbl: true,
//             ritMdcd: true,
//             sepType: "test",
//             sepDnlCrtr: "test",
//             sepOutcm: "test",
//             sepEfctvDt: "2022-04-12",
//             sep: true,
//             sepCmmts: "test",
//             sepacAptc: true,
//             sepacMnthlyAmt: 45634535,
//             sepacAnnAmt: 3453678,
//             sepacCsr: true,
//             sepacCsrLvl: "test",
//             sepacQhp: true,
//             sepacMdcd: true,
//             sepacChip: true,
//             sepacSep: true,
//             sepacCtstrphc: true,
//             sepacExemp: true,
//             sepacNoAwd: true,
//             sepacDisp: "test",
//             ednAptc: true,
//             aptcMonthlyAmt: 76684234,
//             aptcAnnualAmt: 423245576,
//             ednCsr: true,
//             ednCsrLevel: "true",
//             ednQhp: true,
//             ednMedicAid: true,
//             ednSep: true,
//             ednChip: true,
//             ednCstrphc: true,
//             ednExempetion: true,
//             hicsacAptc: true,
//             hicsacMnthlyAmt: 546456,
//             hicsacAnnAmt: 55546645646,
//             hicsacCsr: true,
//             hicsacCsrLvl: "true",
//             hicsacQhp: true,
//             hicsacMdcd: true,
//             hicsacChip: true,
//             hicsacSep: true,
//             hicsacCtstrphc: true,
//             hicsacExemp: true,
//             hicsacNoAwd: true,
//             hicsacDisp: "test",
//             cnstdEdnAptc: true,
//             cnstdMonthlyAmt: 45453446,
//             cnstdAnnualAmt: 3665643543,
//             cnstdEdnCsr: true,
//             cnstdEdnCsrLvl: "test",
//             cnstdEdnQhp: true,
//             cnstdEdnMdcd: true,
//             cnstdEdnChip: true,
//             cnstdEdnSep: true,
//             cnsdtdEdnCtstrphc: true,
//             cnstdEdnExemp: true,
//             cnstdEdnEcn: "test",
//             cnstdEdnDisp: "test",
//             cnstdEdnDispDate: "2022-04-12",
//             dob: "1986-04-12"
//         },
//         {
//             contactId: "9e7ef627-e09a-4274-906e-8652d0787d85",
//             appealId: "APL-1106",
//             createDateTime: "2022-05-11T11:28:56",
//             createOprtr: null,
//             creaeOptrName: null,
//             updateDateTime: "2022-08-02T15:29:38",
//             updateOptr: null,
//             updateOprtName: null,
//             type: null,
//             prsnType: null,
//             primaryContact: false,
//             sfx: null,
//             firstName: "TestF",
//             middleName: "TestM",
//             lastName: "TestL",
//             Dob: null,
//             emplrName: null,
//             dtSgnd: null,
//             sgntrInd: false,
//             adrSameAsApllant: false,
//             authrztn: null,
//             ubleToContact: false,
//             langAstnc: false,
//             spkLang: null,
//             wrtnLang: null,
//             vrfctnType: null,
//             ackAdr: false,
//             efctvStrtDt: null,
//             efctvEndDt: null,
//             authrzgAplntSgtr: false,
//             aplntSgndDt: null,
//             authrzdRprsntvSgntr: false,
//             raprsntvSgndDt: null,
//             acAptc: true,
//             acMonthlyAmt: 2000,
//             acAnnualAmt: 3500,
//             acCsr: true,
//             acCsrLevel: "true",
//             acQhp: false,
//             acMdcd: true,
//             acChip: true,
//             acSep: true,
//             acCtstrphc: true,
//             acExemption: true,
//             acNoAward: true,
//             acDisp: "test",
//             adacAptc: true,
//             adacMonthlyAmt: 123445,
//             adacAnnAmount: 1234567,
//             adacCsr: true,
//             adacCsrLevel: "test1",
//             adacQhp: true,
//             adacMdcd: true,
//             adacChip: true,
//             adacSep: true,
//             adacCtstrphc: true,
//             adacExemp: true,
//             adacNoAward: true,
//             adacDisp: "djtest1",
//             exempEcn: "djtest1",
//             exempIndvdlExemp: "test",
//             exempBgnDt: "2022-04-13",
//             exempEndDt: "2022-04-13",
//             exempOutcm: "test",
//             exempCmmts: "test",
//             pbacAptc: true,
//             pbacMonthlyAmt: 123,
//             pbacAnnaulAmt: 7456,
//             pbacCsr: true,
//             pbacCsrLevel: "test",
//             pbacPhp: true,
//             pbacMdcd: true,
//             pbacChip: true,
//             pbacSep: true,
//             pbacCtstrphc: true,
//             pbacExemp: true,
//             pbacNoAwd: true,
//             pbacDisp: "test",
//             ritAnnualIncome: true,
//             ritCitizenship: true,
//             ritImgrtn: true,
//             ritEscMec: true,
//             ritNonEscMec: true,
//             ritTrbl: true,
//             ritMdcd: true,
//             sepType: "test",
//             sepDnlCrtr: "test",
//             sepOutcm: "test",
//             sepEfctvDt: "2022-04-12",
//             sep: true,
//             sepCmmts: "test",
//             sepacAptc: true,
//             sepacMnthlyAmt: 45634535,
//             sepacAnnAmt: 3453678,
//             sepacCsr: true,
//             sepacCsrLvl: "test",
//             sepacQhp: true,
//             sepacMdcd: true,
//             sepacChip: true,
//             sepacSep: true,
//             sepacCtstrphc: true,
//             sepacExemp: true,
//             sepacNoAwd: true,
//             sepacDisp: "test",
//             ednAptc: true,
//             aptcMonthlyAmt: 76684234,
//             aptcAnnualAmt: 423245576,
//             ednCsr: true,
//             ednCsrLevel: "true",
//             ednQhp: true,
//             ednMedicAid: true,
//             ednSep: true,
//             ednChip: true,
//             ednCstrphc: true,
//             ednExempetion: true,
//             hicsacAptc: true,
//             hicsacMnthlyAmt: 546456,
//             hicsacAnnAmt: 55546645646,
//             hicsacCsr: true,
//             hicsacCsrLvl: "true",
//             hicsacQhp: true,
//             hicsacMdcd: true,
//             hicsacChip: true,
//             hicsacSep: true,
//             hicsacCtstrphc: true,
//             hicsacExemp: true,
//             hicsacNoAwd: true,
//             hicsacDisp: "test",
//             cnstdEdnAptc: true,
//             cnstdMonthlyAmt: 45453446,
//             cnstdAnnualAmt: 3665643543,
//             cnstdEdnCsr: true,
//             cnstdEdnCsrLvl: "test",
//             cnstdEdnQhp: true,
//             cnstdEdnMdcd: true,
//             cnstdEdnChip: true,
//             cnstdEdnSep: true,
//             cnsdtdEdnCtstrphc: true,
//             cnstdEdnExemp: true,
//             cnstdEdnEcn: "test",
//             cnstdEdnDisp: "test",
//             cnstdEdnDispDate: "2022-04-12",
//             dob: null
//         }
//     ],
//     intakeObject: {
//         accommFlag: false,
//         accommReq: [],
//         ackNotice: "",
//         ackNoticeDate: "",
//         ackNoticeGranted: "",
//         aplSubmittedBy: "Appellant",
//         appCallReleaseHold: false,
//         appReasonForAppeal: "",
//         decisionDate: "",
//         eacmsRecievedDate: "2022-04-30T12:59:11.33",
//         eligDecision: "",
//         expComments: "My TestingComments",
//         expFlag: true,
//         expFor: "Expidite",
//         expReqGranted: true,
//         expedited: "Expidite",
//         formType: "Assessment State",
//         intakeType: "Return Mail",
//         langAssitComments: "",
//         langAssitFlag: false,
//         languageAssistReq: [{}],
//         mktplcDecision: "",
//         ndEndDate: "2022-04-30T12:59:11.33",
//         ndFlag: true,
//         ndName: "My Testing",
//         ndStartDate: "2022-04-30T12:59:11.33",
//         openStatusDate: "2022-04-30T12:59:11.33",
//         pendedReason: "Disaster Extension ",
//         pendedReqEndDate: "2022-04-30T12:59:11.332",
//         pendedReqStartDate: "2022-04-12T12:59:11.332",
//         phase: "NO DATA",
//         phaseChangedDate: "",
//         planYear: "2022",
//         receiptType: "On-line",
//         recieptDate: "2022-04-30T12:59:11.33",
//         reopenPhase: "",
//         smah: false,
//         state: "",
//         stateModel: "SBM",
//         status: "New",
//         xReference: "Some Value",
//         xReferenceType: "Appellant on another appeal"
//     },
//     adjudicationObject: {
//         ackmtNtcMailedDate: "2022-04-12",
//         acsTaxData: true,
//         actnNtcSentDt: null,
//         actnneedatcall: "test",
//         actnneedbyeaos: "test",
//         actntakendt: "2022-04-12",
//         adjEffId: "e2fccd15-3e39-4a88-b1d1-96cd50f368cf",
//         adjEffInfo: [],
//         adjKpiAfourPbDate: "2022-04-12",
//         adjKpiAoneDate: "2022-04-12",
//         adjKpiAtwoDate: "2022-04-12",
//         adjPhase: "test1",
//         adjRFIResDates: [],
//         afrdbltyPctg: 789,
//         aplDcsnDate: "2022-04-12",
//         aplInprogNtcSentDt: null,
//         aplclsfctndt: null,
//         aplfileddt: "2022-04-12",
//         aplrcvdmmsdt: "2022-04-12",
//         benchMark: true,
//         busnsName: "test",
//         clsrdt: "2022-04-12",
//         cnstdEDNDate: "2022-04-12",
//         cnstdEdnApplcnDate: "2022-04-12",
//         cnstdEdnAtstdIncome: 535345345345,
//         cnstdEdnComments: "test",
//         cnstdEdnFplPctg: 345345345345,
//         cntstdEdnOutcome: "test",
//         createOperator: "DJtest",
//         eactCompletedBy: "DJ1",
//         eactCompletedDate: "2022-07-14",
//         ednAplcnDate: "2022-04-12",
//         ednAtstdIncome: 5433453,
//         ednComments: "test",
//         ednDate: "2022-04-22",
//         ednFplPctg: 45654757,
//         efctvRqstdDate: "2022-04-12",
//         effPhase: "test1",
//         escMec: true,
//         escMecAfrdblty: "test",
//         escMecType: "test",
//         evaltnGrntdDate: null,
//         evaltnOutcome: null,
//         exempComments: "test1",
//         exempDocsRequested: "test1",
//         exempRequestNumber: 12345,
//         exmpPhase: "test1",
//         extensionDate: "2022-04-12",
//         fairlRcncl: true,
//         ftrToolDueDate: "2022-04-12",
//         heargdcsndt: "2022-04-12",
//         hicsInfo: [],
//         hicsMatchAd: true,
//         houseHoldIncome: 456,
//         icoAtstdIncome: 97793247923,
//         id: "02",
//         inconsDocuments: [],
//         inconsDtls: [],
//         inconsResolvedFfm: "test",
//         irCicDate: "2022-04-12",
//         irCicPerformed: "test",
//         irNtcRespDueDt: null,
//         irNtcSent: null,
//         irNtcStsf: null,
//         irNtcStsfDt: null,
//         irntcexprtndt: "2022-04-12",
//         irntcsentdt: "2022-04-12",
//         iroAdrdbltyPctg: "test",
//         iroFplPctg: 42424242342342,
//         irresprcvddt: "2022-04-12",
//         lowstSlfPlanCost: 56565656,
//         marFilingSeparately: true,
//         marketPlaceAplcnId: null,
//         mdcdorchipdnl: null,
//         mdcdorchiptrmntn: null,
//         mdcdorchipunwinding: null,
//         moenDate: "2022-04-12",
//         noFinclAstnc: true,
//         noRetroactGrntd: false,
//         nonEscMec: true,
//         nonEscMecType: "test",
//         nonTaxFiler: true,
//         outcomeWithThreshhold: "test",
//         outstandingDocuments: [],
//         overFourHundred: true,
//         particagree: "test",
//         pbEvaluation: [],
//         pendBnftComments: "test",
//         pendBnftEfctvDate: "2022-04-12",
//         pendBnftElgbl: true,
//         pendBnftRqstDate: "2022-04-12",
//         pendBnftTrmntnDate: "2022-04-12",
//         postIRMatchIR: true,
//         postIrNtcSent: null,
//         postIrNtcSentDt: null,
//         postirdt: "2022-04-12",
//         premiumAmount: 123,
//         priorEnrlmntHstry: null,
//         priorIncons: null,
//         rdtrmntn: null,
//         retroActGrntd: "test1",
//         retroActGrntdDate: "2022-04-12",
//         retroActRqstdDate: "2022-04-12",
//         retroactElgblDt: null,
//         retroactRqstd: "test1",
//         rfiRespRecvdDt: null,
//         rfiResponseDueDt: null,
//         rfiSentDate: null,
//         rspnsKpiAtwoDate: "2022-04-12",
//         rvsdIrDt: null,
//         rvsdirelgbl: "test",
//         rvsdirenddt: "2022-04-12",
//         rvsdiroutcm: "test",
//         rvsdirrsn: "test",
//         rvsdirrspns: "test",
//         rvsdirstartdt: "2022-04-12",
//         schdlheargdt: "2022-04-12",
//         schdlheargsentdt: "2022-04-12",
//         secondIrElgbl: null,
//         sepEndDt: null,
//         sepExprtnDate: "2022-04-12",
//         sepGrntd: null,
//         sepMatchAd: true,
//         sepOpenDt: null,
//         sercoEfctatnDt: null,
//         spclNtcGrp: true,
//         timely: null,
//         tolrsn: "test",
//         tolstartdt: "2022-04-12",
//         tolstopdt: "2022-04-12",
//         underOneHundFpl: true,
//         updateOperator: "test1",
//         verificationTools: [],
//     },
//     hearingObject: {},
//     effectuationObject: {},
// }
// const B_OBJ = {
//     ackmtNtcMailedDate: "2022-04-12",
//     acsTaxData: true,
//     actnNtcSentDt: null,
//     actnneedatcall: "test",
//     actnneedbyeaos: "test",
//     actntakendt: "2022-04-12",
//     adjEffId: "e2fccd15-3e39-4a88-b1d1-96cd50f368cf",
//     adjEffInfo: [],
//     adjKpiAfourPbDate: "2022-04-12",
//     adjKpiAoneDate: "2022-04-12",
//     adjKpiAtwoDate: "2022-04-12",
//     adjPhase: "test1",
//     adjRFIResDates: [],
//     afrdbltyPctg: 789,
//     aplDcsnDate: "2022-04-12",
//     aplInprogNtcSentDt: null,
//     aplclsfctndt: null,
//     aplfileddt: "2022-04-12",
//     aplrcvdmmsdt: "2022-04-12",
//     benchMark: true,
//     busnsName: "test",
//     clsrdt: "2022-04-12",
//     cnstdEDNDate: "2022-04-12",
//     cnstdEdnApplcnDate: "2022-04-12",
//     cnstdEdnAtstdIncome: 535345345345,
//     cnstdEdnComments: "test",
//     cnstdEdnFplPctg: 345345345345,
//     cntstdEdnOutcome: "test",
//     createOperator: "DJtest",
//     eactCompletedBy: "DJ1",
//     eactCompletedDate: "2022-07-14",
//     ednAplcnDate: "2022-04-12",
//     ednAtstdIncome: 5433453,
//     ednComments: "test",
//     ednDate: "2022-04-22",
//     ednFplPctg: 45654757,
//     efctvRqstdDate: "2022-04-12",
//     effPhase: "test1",
//     escMec: true,
//     escMecAfrdblty: "test",
//     escMecType: "test",
//     evaltnGrntdDate: null,
//     evaltnOutcome: null,
//     exempComments: "test1",
//     exempDocsRequested: "test1",
//     exempRequestNumber: 12345,
//     exmpPhase: "test1",
//     extensionDate: "2022-04-12",
//     fairlRcncl: true,
//     ftrToolDueDate: "2022-04-12",
//     heargdcsndt: "2022-04-12",
//     hicsInfo: [],
//     hicsMatchAd: true,
//     houseHoldIncome: 456,
//     icoAtstdIncome: 97793247923,
//     id: "02",
//     inconsDocuments: [],
//     inconsDtls: [],
//     inconsResolvedFfm: "test",
//     irCicDate: "2022-04-12",
//     irCicPerformed: "test",
//     irNtcRespDueDt: null,
//     irNtcSent: null,
//     irNtcStsf: null,
//     irNtcStsfDt: null,
//     irntcexprtndt: "2022-04-12",
//     irntcsentdt: "2022-04-12",
//     iroAdrdbltyPctg: "test",
//     iroFplPctg: 42424242342342,
//     irresprcvddt: "2022-04-12",
//     lowstSlfPlanCost: 56565656,
//     marFilingSeparately: true,
//     marketPlaceAplcnId: null,
//     mdcdorchipdnl: null,
//     mdcdorchiptrmntn: null,
//     mdcdorchipunwinding: null,
//     moenDate: "2022-04-12",
//     noFinclAstnc: true,
//     noRetroactGrntd: false,
//     nonEscMec: true,
//     nonEscMecType: "test",
//     nonTaxFiler: true,
//     outcomeWithThreshhold: "test",
//     outstandingDocuments: [],
//     overFourHundred: true,
//     particagree: "test",
//     pbEvaluation: [],
//     pendBnftComments: "test",
//     pendBnftEfctvDate: "2022-04-12",
//     pendBnftElgbl: true,
//     pendBnftRqstDate: "2022-04-12",
//     pendBnftTrmntnDate: "2022-04-12",
//     postIRMatchIR: true,
//     postIrNtcSent: null,
//     postIrNtcSentDt: null,
//     postirdt: "2022-04-12",
//     premiumAmount: 123,
//     priorEnrlmntHstry: null,
//     priorIncons: null,
//     rdtrmntn: null,
//     retroActGrntd: "test1",
//     retroActGrntdDate: "2022-04-12",
//     retroActRqstdDate: "2022-04-12",
//     retroactElgblDt: null,
//     retroactRqstd: "test1",
//     rfiRespRecvdDt: null,
//     rfiResponseDueDt: null,
//     rfiSentDate: null,
//     rspnsKpiAtwoDate: "2022-04-12",
//     rvsdIrDt: null,
//     rvsdirelgbl: "test",
//     rvsdirenddt: "2022-04-12",
//     rvsdiroutcm: "test",
//     rvsdirrsn: "test",
//     rvsdirrspns: "test",
//     rvsdirstartdt: "2022-04-12",
//     schdlheargdt: "2022-04-12",
//     schdlheargsentdt: "2022-04-12",
//     secondIrElgbl: null,
//     sepEndDt: null,
//     sepExprtnDate: "2022-04-12",
//     sepGrntd: null,
//     sepMatchAd: true,
//     sepOpenDt: null,
//     sercoEfctatnDt: null,
//     spclNtcGrp: true,
//     timely: null,
//     tolrsn: "test",
//     tolstartdt: "2022-04-12",
//     tolstopdt: "2022-04-12",
//     underOneHundFpl: true,
//     updateOperator: "test1",
//     verificationTools: [],
// }